from django.urls import path, re_path

from . import handrive_views, sync_views, views

app_name = 'main'

urlpatterns = [
    path("favicon.ico", views.favicon_ico, name="favicon_ico"),
    path("robots.txt", views.robots_txt, name="robots_txt"),
    path("sitemap.xml", views.sitemap_xml, name="sitemap_xml"),
    # PWA endpoints (manifest + service worker)
    path("manifest.webmanifest", views.pwa_manifest, name="pwa_manifest"),
    path("service-worker.js", views.service_worker, name="service_worker"),
    path('', views.none, name='none'),

    # ── Sync API (/api/sync/) ────────────────────────────────────────────────
    path("api/sync/auth/token",   sync_views.sync_auth_token,   name="sync_auth_token"),
    path("api/sync/auth/refresh", sync_views.sync_auth_refresh, name="sync_auth_refresh"),
    path("api/sync/files",        sync_views.sync_files_list,   name="sync_files_list"),
    path("api/sync/files/init-upload", sync_views.sync_files_init_upload, name="sync_files_init_upload"),
    path("api/sync/uploads/<str:upload_id>/data", sync_views.sync_upload_data, name="sync_upload_data"),
    path("api/sync/files/complete",    sync_views.sync_files_complete,    name="sync_files_complete"),
    path("api/sync/files/<uuid:file_id>/download-url", sync_views.sync_files_download_url, name="sync_files_download_url"),
    path("api/sync/files/<uuid:file_id>/download", sync_views.sync_files_download_proxy, name="sync_files_download_proxy"),
    path("api/sync/files/<uuid:file_id>",              sync_views.sync_files_delete,        name="sync_files_delete"),
    path("api/sync/files/<uuid:file_id>/move",         sync_views.sync_files_move,          name="sync_files_move"),
    path("api/sync/changes",      sync_views.sync_changes,      name="sync_changes"),
    path("api/sync/storage-mode", sync_views.sync_storage_mode, name="sync_storage_mode"),
    path("api/sync/me",           sync_views.sync_me,           name="sync_me"),
    path("api/sync/auth/handrive-callback", handrive_views.handrive_callback_poll, name="handrive_callback_poll"),
    # ────────────────────────────────────────────────────────────────────────

    path('handrive', handrive_views.handrive_root, name='handrive_root'),
    path('handrive/', handrive_views.handrive_root),
    path('handrive/list', handrive_views.handrive_root, name='handrive_list_root'),
    path('handrive/list/', handrive_views.handrive_root),
    path('handrive/write', handrive_views.handrive_write, name='handrive_write'),
    path('handrive/write/', handrive_views.handrive_write),
    path('signup', handrive_views.handrive_signup, name='handrive_signup'),
    path('signup/', handrive_views.handrive_signup),
    path('login', handrive_views.handrive_login, name='handrive_login'),
    path('login/', handrive_views.handrive_login),
    path('login/handrive', handrive_views.handrive_login_bridge, name='handrive_login_bridge'),
    path('login/handrive/', handrive_views.handrive_login_bridge),
    path('logout', handrive_views.handrive_logout, name='handrive_logout'),
    path('logout/', handrive_views.handrive_logout),
    path('privacy', views.privacy_page, name='privacy_page'),
    path('privacy/', views.privacy_page),
    path('terms', views.terms_page, name='terms_page'),
    path('terms/', views.terms_page),
    path('licenses', views.licenses_page, name='licenses_page'),
    path('licenses/', views.licenses_page),
    path('handrive/ops/apply-static', handrive_views.handrive_ops_apply_static, name='handrive_ops_apply_static'),
    path('handrive/ops/apply-static/', handrive_views.handrive_ops_apply_static),
    path('handrive/api/list', handrive_views.handrive_api_list, name='handrive_api_list'),
    path('handrive/api/search', handrive_views.handrive_api_search, name='handrive_api_search'),
    path('handrive/api/save', handrive_views.handrive_api_save, name='handrive_api_save'),
    path('handrive/api/preview', handrive_views.handrive_api_preview, name='handrive_api_preview'),
    path('handrive/api/rename', handrive_views.handrive_api_rename, name='handrive_api_rename'),
    path('handrive/api/delete', handrive_views.handrive_api_delete, name='handrive_api_delete'),
    path('handrive/api/mkdir', handrive_views.handrive_api_mkdir, name='handrive_api_mkdir'),
    path('handrive/api/move', handrive_views.handrive_api_move, name='handrive_api_move'),
    path('handrive/api/upload', handrive_views.handrive_api_upload, name='handrive_api_upload'),
    path('handrive/api/upload/cancel', handrive_views.handrive_api_upload_cancel, name='handrive_api_upload_cancel'),
    path('handrive/api/download', handrive_views.handrive_api_download, name='handrive_api_download'),
    path('handrive/api/pdf-preview', handrive_views.handrive_api_pdf_preview, name='handrive_api_pdf_preview'),
    path('handrive/api/acl', handrive_views.handrive_api_acl, name='handrive_api_acl'),
    path('handrive/api/acl-options', handrive_views.handrive_api_acl_options, name='handrive_api_acl_options'),
    path('handrive/api/url-share', handrive_views.handrive_api_url_share, name='handrive_api_url_share'),
    path('handrive/api/sync-settings', handrive_views.handrive_api_sync_settings, name='handrive_api_sync_settings'),
    path('handrive/api/map/create', handrive_views.handrive_api_map_create, name='handrive_api_map_create'),
    path('handrive/api/map/data', handrive_views.handrive_api_map_data, name='handrive_api_map_data'),
    path('handrive/api/map/data/save', handrive_views.handrive_api_map_data_save, name='handrive_api_map_data_save'),
    path('handrive/api/map/icon-upload', handrive_views.handrive_api_map_icon_upload, name='handrive_api_map_icon_upload'),
    path('handrive/api/map/icon-delete', handrive_views.handrive_api_map_icon_delete, name='handrive_api_map_icon_delete'),
    path('handrive/api/folder-icon', handrive_views.handrive_api_folder_icon_serve, name='handrive_api_folder_icon_serve'),
    path('handrive/api/folder-icon/', handrive_views.handrive_api_folder_icon_serve),
    path('handrive/api/folder-icon/upload', handrive_views.handrive_api_folder_icon_upload, name='handrive_api_folder_icon_upload'),
    path('handrive/api/folder-icon/delete', handrive_views.handrive_api_folder_icon_delete, name='handrive_api_folder_icon_delete'),
    path('handrive/api/map/image-upload', handrive_views.handrive_api_map_attachment_upload, name='handrive_api_map_attachment_upload'),
    path('handrive/api/map-image/', handrive_views.handrive_api_map_image, name='handrive_api_map_image'),
    path('handrive/api/login-captcha-status', handrive_views.handrive_api_login_captcha_status, name='handrive_api_login_captcha_status'),
    path('handrive/share/<str:owner_username>/<str:share_slug>', handrive_views.handrive_shared_view, name='handrive_shared_view'),
    path('handrive/share/<str:owner_username>/<str:share_slug>/', handrive_views.handrive_shared_view),
    path('handrive/<path:folder_path>/list', handrive_views.handrive_list, name='handrive_list'),
    path('handrive/<path:folder_path>/list/', handrive_views.handrive_list),
    path('handrive/map-editor/<path:map_path>', handrive_views.handrive_map_editor, name='handrive_map_editor'),
    path('handrive/map-viewer/<path:map_path>', handrive_views.handrive_map_viewer, name='handrive_map_viewer'),
    path('handrive/<path:doc_path>', handrive_views.handrive_view, name='handrive_view'),
    path('docs', handrive_views.handrive_root_legacy_redirect),
    path('docs/', handrive_views.handrive_root_legacy_redirect),
    path('docs/list', handrive_views.handrive_list_root_legacy_redirect),
    path('docs/list/', handrive_views.handrive_list_root_legacy_redirect),
    path('docs/write', handrive_views.handrive_write_legacy_redirect),
    path('docs/write/', handrive_views.handrive_write_legacy_redirect),
    path('docs/<path:folder_path>/list', handrive_views.handrive_list_legacy_redirect),
    path('docs/<path:folder_path>/list/', handrive_views.handrive_list_legacy_redirect),
    path('docs/<path:doc_path>', handrive_views.handrive_view_legacy_redirect),
    re_path(r'^(?P<ui_lang>ko|en)/handrive/?$', handrive_views.handrive_root, name='handrive_root_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/handrive/list/?$', handrive_views.handrive_root, name='handrive_list_root_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/handrive/write/?$', handrive_views.handrive_write, name='handrive_write_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/docs/?$', handrive_views.handrive_root),
    re_path(r'^(?P<ui_lang>ko|en)/docs/list/?$', handrive_views.handrive_root),
    re_path(r'^(?P<ui_lang>ko|en)/docs/write/?$', handrive_views.handrive_write),
    re_path(r'^(?P<ui_lang>ko|en)/docs/(?P<folder_path>.+)/list/?$', handrive_views.handrive_list),
    re_path(r'^(?P<ui_lang>ko|en)/docs/(?P<doc_path>.+)/?$', handrive_views.handrive_view),
    re_path(r'^(?P<ui_lang>ko|en)/signup/?$', handrive_views.handrive_signup, name='handrive_signup_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/login/?$', handrive_views.handrive_login, name='handrive_login_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/logout/?$', handrive_views.handrive_logout, name='handrive_logout_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/privacy/?$', views.privacy_page, name='privacy_page_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/terms/?$', views.terms_page, name='terms_page_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/licenses/?$', views.licenses_page, name='licenses_page_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/handrive/ops/apply-static/?$', handrive_views.handrive_ops_apply_static, name='handrive_ops_apply_static_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/handrive/share/(?P<owner_username>[^/]+)/(?P<share_slug>[^/]+)/?$', handrive_views.handrive_shared_view, name='handrive_shared_view_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/handrive/(?P<folder_path>.+)/list/?$', handrive_views.handrive_list, name='handrive_list_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/handrive/map-editor/(?P<map_path>.+)/?$', handrive_views.handrive_map_editor, name='handrive_map_editor_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/handrive/map-viewer/(?P<map_path>.+)/?$', handrive_views.handrive_map_viewer, name='handrive_map_viewer_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/handrive/(?P<doc_path>.+)/?$', handrive_views.handrive_view, name='handrive_view_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/$', views.none, name='none_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/portfolio/$', views.portfolio_root_redirect, name='main_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/portfolio/write/?$', views.portfolio_write, name='portfolio_write_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/portfolio/(?P<user_id>[A-Za-z0-9_.-]+)/$', views.portfolio_user, name='portfolio_user_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/project/(?P<project_id>\d+)/$', views.ProjectDetail, name='ProjectDetail_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/project/sample/(?P<sample_id>\d+)/$', views.DummyProjectDetail, name='DummyProjectDetail_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/project/(?P<user_id>[A-Za-z0-9_.-]+)/(?P<project_number>\d+)/$', views.ProjectDetailByUser, name='ProjectDetail_user_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/fun/Salvations_Edge_4/$', views.Salvations_Edge_4, name='Salvations_Edge_4_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/fun/Stratagem_Hero/$', views.Stratagem_Hero_page, name='Stratagem_Hero_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/fun/Stratagem_Hero/Scoreboard/$', views.Stratagem_Hero_Scoreboard_page, name='Stratagem_Hero_Scoreboard_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/fun/minigame/?$', views.minigame_page, name='minigame_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/fun/bubble/?$', views.bubble_page, name='bubble_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/fun/text-speaki/?$', views.text_bubble_page, name='text_bubble_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/fun/bumpercar-spiky/admin/?$', views.bumpercar_spiky_admin_page, name='bumpercar_spiky_admin_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/fun/bumpercar-spiky/set-npc-health/?$', views.bumpercar_spiky_set_npc_health, name='bumpercar_spiky_set_npc_health_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/fun/bumpercar-spiky/restart-server/?$', views.bumpercar_spiky_restart_server, name='bumpercar_spiky_restart_server_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/fun/bumpercar-spiky/?$', views.hanplanet_multiplayer_page, name='bumpercar_spiky_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/fun/raise-speaki/?$', views.raise_speaki_page, name='raise_speaki_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/fun/Stratagem_Hero/add_score/$', views.add_score, name='add_score_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/Salvations_Edge_4/$', views.salvations_edge_legacy_redirect),
    re_path(r'^(?P<ui_lang>ko|en)/Stratagem_Hero/$', views.stratagem_hero_legacy_redirect),
    re_path(r'^(?P<ui_lang>ko|en)/Stratagem_Hero/Scoreboard/$', views.stratagem_hero_scoreboard_legacy_redirect),
    re_path(r'^(?P<ui_lang>ko|en)/minigame/?$', views.minigame_legacy_redirect),
    re_path(r'^(?P<ui_lang>ko|en)/bubble/?$', views.bubble_legacy_redirect),
    re_path(r'^(?P<ui_lang>ko|en)/hanplanet-multiplayer/?$', views.hanplanet_multiplayer_legacy_redirect),
    re_path(r'^(?P<ui_lang>ko|en)/bumpercar-spiky/?$', views.hanplanet_multiplayer_legacy_redirect),
    re_path(r'^(?P<ui_lang>ko|en)/Stratagem_Hero/add_score/$', views.add_score),
    re_path(r'^(?P<ui_lang>ko|en)/comment/create/(?P<project_id>\d+)/$', views.ProjectComment_create, name='ProjectComment_create_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/root-shortcuts/$', views.root_shortcuts, name='root_shortcuts_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/root-shortcuts/reorder/$', views.root_shortcuts_reorder, name='root_shortcuts_reorder_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/root-shortcuts/(?P<shortcut_id>\d+)/$', views.root_shortcuts_detail, name='root_shortcuts_detail_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/theme-preference/$', views.theme_preference, name='theme_preference_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/user-preferences/$', views.user_preferences, name='user_preferences_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/game-auth-token/$', views.game_auth_token, name='game_auth_token_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/account/profile-image/?$', views.account_profile_image_upload, name='account_profile_image_upload_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/chat/$', views.chat_with_ai, name='chat_with_ai_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/translate/$', views.translate_text, name='translate_text_lang'),
    path('portfolio/', views.main_legacy_redirect, name='main'),
    path('portfolio/write', views.portfolio_write_legacy_redirect, name='portfolio_write_no_slash'),
    path('portfolio/write/', views.portfolio_write_legacy_redirect, name='portfolio_write'),
    path('portfolio/<str:user_id>/', views.portfolio_user_legacy_redirect, name='portfolio_user'),
    path('project/<int:project_id>/', views.project_detail_legacy_redirect, name='ProjectDetail'),
    path('project/<str:user_id>/<int:project_number>/', views.project_detail_user_legacy_redirect, name='ProjectDetail_user'),
    path('project/sample/<int:sample_id>/', views.dummy_project_detail_legacy_redirect, name='DummyProjectDetail'),
    path('fun/Salvations_Edge_4/', views.salvations_edge_legacy_redirect, name='Salvations_Edge_4'),
    path('fun/Stratagem_Hero/', views.stratagem_hero_legacy_redirect, name='Stratagem_Hero'),
    path('fun/Stratagem_Hero/Scoreboard/', views.stratagem_hero_scoreboard_legacy_redirect, name='Stratagem_Hero_Scoreboard'),
    path('fun/minigame', views.minigame_legacy_redirect, name='minigame_no_slash'),
    path('fun/minigame/', views.minigame_legacy_redirect, name='minigame'),
    path('fun/bubble', views.bubble_legacy_redirect, name='bubble_no_slash'),
    path('fun/bubble/', views.bubble_legacy_redirect, name='bubble'),
    path('fun/text-speaki', views.text_bubble_page, name='text_bubble_no_slash'),
    path('fun/text-speaki/', views.text_bubble_page, name='text_bubble'),
    path('api/nyt-article/', views.nyt_article_api, name='nyt_article_api'),
    path('fun/hanplanet-multiplayer', views.hanplanet_multiplayer_legacy_redirect, name='hanplanet_multiplayer_no_slash'),
    path('fun/hanplanet-multiplayer/', views.hanplanet_multiplayer_legacy_redirect, name='hanplanet_multiplayer'),
    path('fun/bumpercar-spiky', views.hanplanet_multiplayer_legacy_redirect, name='bumpercar_spiky_no_slash'),
    path('fun/bumpercar-spiky/admin', views.bumpercar_spiky_admin_legacy_redirect, name='bumpercar_spiky_admin_no_slash'),
    path('fun/bumpercar-spiky/admin/', views.bumpercar_spiky_admin_legacy_redirect, name='bumpercar_spiky_admin'),
    path('fun/bumpercar-spiky/', views.hanplanet_multiplayer_legacy_redirect, name='bumpercar_spiky'),
    path('fun/raise-speaki', views.raise_speaki_page, name='raise_speaki_no_slash'),
    path('fun/raise-speaki/', views.raise_speaki_page, name='raise_speaki'),
    path('fun/Stratagem_Hero/add_score/', views.add_score, name='add_score'),
    path('Salvations_Edge_4/', views.salvations_edge_legacy_redirect),
    path('Stratagem_Hero/', views.stratagem_hero_legacy_redirect),
    path('Stratagem_Hero/Scoreboard/', views.stratagem_hero_scoreboard_legacy_redirect),
    path('minigame', views.minigame_legacy_redirect),
    path('minigame/', views.minigame_legacy_redirect),
    path('bubble', views.bubble_legacy_redirect),
    path('bubble/', views.bubble_legacy_redirect),
    path('hanplanet-multiplayer', views.hanplanet_multiplayer_legacy_redirect),
    path('hanplanet-multiplayer/', views.hanplanet_multiplayer_legacy_redirect),
    path('bumpercar-spiky', views.hanplanet_multiplayer_legacy_redirect),
    path('bumpercar-spiky/', views.hanplanet_multiplayer_legacy_redirect),
    path('raise-speaki', views.raise_speaki_page),
    path('raise-speaki/', views.raise_speaki_page),
    path('Stratagem_Hero/add_score/', views.add_score),
    path('comment/create/<int:project_id>/', views.ProjectComment_create, name='ProjectComment_create'),
    path('api/root-shortcuts/', views.root_shortcuts, name='root_shortcuts'),
    path('api/root-shortcuts/reorder/', views.root_shortcuts_reorder, name='root_shortcuts_reorder'),
    path('api/root-shortcuts/<int:shortcut_id>/', views.root_shortcuts_detail, name='root_shortcuts_detail'),
    path('api/theme-preference/', views.theme_preference, name='theme_preference'),
    path('api/user-preferences/', views.user_preferences, name='user_preferences'),
    path('api/game-auth-token/', views.game_auth_token, name='game_auth_token'),
    path('api/internal/bumpercar-spiky/stats/', views.bumpercar_spiky_stats_record, name='bumpercar_spiky_stats_record'),
    path('account/profile-image/', views.account_profile_image_upload, name='account_profile_image_upload'),
    path('api/chat/', views.chat_with_ai, name='chat_with_ai'),
    path('api/translate/', views.translate_text, name='translate_text'),
    path('api/git/repos/', views.git_repo_create, name='git_repo_create'),
    path('api/git/repos/by-path/', views.git_repo_by_path, name='git_repo_by_path'),
    path('api/git/repos/<int:repo_id>/collaborators/', views.git_repo_collaborator, name='git_repo_collaborator'),
    path('api/git/repos/<int:repo_id>/clone/', views.git_repo_clone_url, name='git_repo_clone_url'),
    path('api/git/repos/<int:repo_id>/status/', views.git_repo_status, name='git_repo_status'),
    path('api/git/repos/<int:repo_id>/retry/', views.git_repo_retry, name='git_repo_retry'),
    path('api/git/repos/<int:repo_id>/branches/', views.git_branch_create, name='git_branch_create'),
    path('api/git/repos/<int:repo_id>/branches/delete/', views.git_branch_delete, name='git_branch_delete'),
    # Git Device Flow 인증
    path('api/git/auth/device/',  views.git_auth_device,  name='git_auth_device'),
    path('api/git/auth/token/',   views.git_auth_token,   name='git_auth_token'),
    path('api/git/auth/approve/', views.git_auth_approve, name='git_auth_approve'),
    path('git-auth/',             views.git_auth_page,    name='git_auth_page'),
    path('git-auth/credential-helper/', views.git_credential_helper_download, name='git_credential_helper_download'),
    path('sync-client/handrive.exe', views.handrive_sync_client_download, name='handrive_sync_client_download'),
    # Gitea SSO 릴레이: 로그인 후 Gitea 자동 로그인
    path('sso/gitea', handrive_views.handrive_gitea_sso_relay, name='gitea_sso_relay'),
    path('logout/bridge', handrive_views.handrive_logout_bridge, name='handrive_logout_bridge'),
    re_path(r'^(?P<ui_lang>ko|en)/logout/bridge/?$', handrive_views.handrive_logout_bridge, name='handrive_logout_bridge_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sync-client/handrive\.exe/?$', views.handrive_sync_client_download, name='handrive_sync_client_download_lang'),
]
