from django.urls import path, re_path

from . import handrive_views, sync_views, views

app_name = 'main'

urlpatterns = [
    path("favicon.ico", views.favicon_ico, name="favicon_ico"),
    path("robots.txt", views.robots_txt, name="robots_txt"),
    path("sitemap.xml", views.sitemap_xml, name="sitemap_xml"),
    # PWA endpoints (manifest + service worker)
    path("manifest.webmanifest", views.pwa_manifest, name="pwa_manifest"),
    path("service-worker.js", views.service_worker, name="service_worker"),
    path('', views.none, name='none'),

    # ── Sync API (/api/sync/) ────────────────────────────────────────────────
    path("api/sync/auth/token",   sync_views.sync_auth_token,   name="sync_auth_token"),
    path("api/sync/auth/refresh", sync_views.sync_auth_refresh, name="sync_auth_refresh"),
    path("api/sync/files",        sync_views.sync_files_list,   name="sync_files_list"),
    path("api/sync/files/init-upload", sync_views.sync_files_init_upload, name="sync_files_init_upload"),
    path("api/sync/uploads/<str:upload_id>/data", sync_views.sync_upload_data, name="sync_upload_data"),
    path("api/sync/files/complete",    sync_views.sync_files_complete,    name="sync_files_complete"),
    path("api/sync/files/<uuid:file_id>/download-url", sync_views.sync_files_download_url, name="sync_files_download_url"),
    path("api/sync/files/<uuid:file_id>/download", sync_views.sync_files_download_proxy, name="sync_files_download_proxy"),
    path("api/sync/files/<uuid:file_id>",              sync_views.sync_files_delete,        name="sync_files_delete"),
    path("api/sync/files/<uuid:file_id>/move",         sync_views.sync_files_move,          name="sync_files_move"),
    path("api/sync/changes",      sync_views.sync_changes,      name="sync_changes"),
    path("api/sync/storage-mode", sync_views.sync_storage_mode, name="sync_storage_mode"),
    path("api/sync/me",           sync_views.sync_me,           name="sync_me"),
    path("api/sync/auth/handrive-callback", handrive_views.handrive_callback_poll, name="handrive_callback_poll"),
    # ────────────────────────────────────────────────────────────────────────

    path('handrive', views.redirect_to_language_prefixed_path, name='handrive_root'),
    path('handrive/', views.redirect_to_language_prefixed_path),
    path('handrive/list', views.redirect_to_language_prefixed_path, name='handrive_list_root'),
    path('handrive/list/', views.redirect_to_language_prefixed_path),
    path('handrive/write', views.redirect_to_language_prefixed_path, name='handrive_write'),
    path('handrive/write/', views.redirect_to_language_prefixed_path),
    path('signup', handrive_views.handrive_signup, name='handrive_signup'),
    path('signup/', handrive_views.handrive_signup),
    path('login', handrive_views.handrive_login, name='handrive_login'),
    path('login/', handrive_views.handrive_login),
    path('auth/github/start', handrive_views.handrive_github_auth_start, name='handrive_github_auth_start'),
    path('auth/github/start/', handrive_views.handrive_github_auth_start),
    path('auth/github/callback', handrive_views.handrive_github_auth_callback, name='handrive_github_auth_callback'),
    path('auth/github/callback/', handrive_views.handrive_github_auth_callback),
    path('auth/google/start', handrive_views.handrive_google_auth_start, name='handrive_google_auth_start'),
    path('auth/google/start/', handrive_views.handrive_google_auth_start),
    path('auth/google/callback', handrive_views.handrive_google_auth_callback, name='handrive_google_auth_callback'),
    path('auth/google/callback/', handrive_views.handrive_google_auth_callback),
    path('api/account/google/unlink', handrive_views.handrive_api_google_unlink, name='handrive_api_google_unlink'),
    path('api/account/google/unlink/', handrive_views.handrive_api_google_unlink),
    path('api/account/google/drive', handrive_views.handrive_api_google_drive_settings, name='handrive_api_google_drive_settings'),
    path('api/account/google/drive/', handrive_views.handrive_api_google_drive_settings),
    path('api/account/google/picker-config', handrive_views.handrive_api_google_picker_config, name='handrive_api_google_picker_config'),
    path('api/account/google/picker-config/', handrive_views.handrive_api_google_picker_config),
    path('api/account/google/drive-items', handrive_views.handrive_api_google_drive_items, name='handrive_api_google_drive_items'),
    path('api/account/google/drive-items/', handrive_views.handrive_api_google_drive_items),
    path('api/account/github/unlink', handrive_views.handrive_api_github_unlink, name='handrive_api_github_unlink'),
    path('api/account/github/unlink/', handrive_views.handrive_api_github_unlink),
    path('api/account/github/repositories', handrive_views.handrive_api_github_repositories, name='handrive_api_github_repositories'),
    path('api/account/github/repositories/', handrive_views.handrive_api_github_repositories),
    path('login/handrive', handrive_views.handrive_login_bridge, name='handrive_login_bridge'),
    path('login/handrive/', handrive_views.handrive_login_bridge),
    path('logout', handrive_views.handrive_logout, name='handrive_logout'),
    path('logout/', handrive_views.handrive_logout),
    path('2fa-verify', handrive_views.handrive_2fa_verify, name='handrive_2fa_verify'),
    path('2fa-verify/', handrive_views.handrive_2fa_verify),
    path('register-email', handrive_views.handrive_register_email, name='handrive_register_email'),
    path('register-email/', handrive_views.handrive_register_email),
    path('privacy', views.privacy_page_unprefixed, name='privacy_page'),
    path('privacy/', views.privacy_page_unprefixed),
    path('terms', views.terms_page_unprefixed, name='terms_page'),
    path('terms/', views.terms_page_unprefixed),
    path('licenses', views.redirect_to_language_prefixed_path, name='licenses_page'),
    path('licenses/', views.redirect_to_language_prefixed_path),
    path('handrive/cli', views.redirect_to_language_prefixed_path, name='hanharness_page'),
    path('handrive/cli/', views.redirect_to_language_prefixed_path),
    path('handrive/cli/download/macos', views.redirect_to_language_prefixed_path, name='hanharness_download'),
    path('handrive/cli/download/macos/', views.redirect_to_language_prefixed_path),
    path('handrive/cli/download/windows', views.redirect_to_language_prefixed_path, name='hanharness_download_windows'),
    path('handrive/cli/download/windows/', views.redirect_to_language_prefixed_path),
    path('handrive/ops/apply-static', handrive_views.handrive_ops_apply_static, name='handrive_ops_apply_static'),
    path('handrive/ops/apply-static/', handrive_views.handrive_ops_apply_static),
    path('handrive/api/list', handrive_views.handrive_api_list, name='handrive_api_list'),
    path('handrive/api/search', handrive_views.handrive_api_search, name='handrive_api_search'),
    path('handrive/api/save', handrive_views.handrive_api_save, name='handrive_api_save'),
    path('handrive/api/spreadsheet/save', handrive_views.handrive_api_spreadsheet_save, name='handrive_api_spreadsheet_save'),
    path('handrive/api/preview', handrive_views.handrive_api_preview, name='handrive_api_preview'),
    path('handrive/api/rename', handrive_views.handrive_api_rename, name='handrive_api_rename'),
    path('handrive/api/delete', handrive_views.handrive_api_delete, name='handrive_api_delete'),
    path('handrive/api/mkdir', handrive_views.handrive_api_mkdir, name='handrive_api_mkdir'),
    path('handrive/api/move', handrive_views.handrive_api_move, name='handrive_api_move'),
    path('handrive/api/archive/extract', handrive_views.handrive_api_archive_extract, name='handrive_api_archive_extract'),
    path('handrive/api/archive/create', handrive_views.handrive_api_archive_create, name='handrive_api_archive_create'),
    path('handrive/api/convert/mp3', handrive_views.handrive_api_convert_mp3, name='handrive_api_convert_mp3'),
    path('handrive/api/upload', handrive_views.handrive_api_upload, name='handrive_api_upload'),
    path('handrive/api/markdown-image-upload', handrive_views.handrive_api_markdown_image_upload, name='handrive_api_markdown_image_upload'),
    path('handrive/api/markdown-image-cleanup', handrive_views.handrive_api_markdown_image_cleanup, name='handrive_api_markdown_image_cleanup'),
    path('handrive/api/upload/cancel', handrive_views.handrive_api_upload_cancel, name='handrive_api_upload_cancel'),
    path('handrive/api/download', handrive_views.handrive_api_download, name='handrive_api_download'),
    path('handrive/api/hls/status', handrive_views.handrive_api_hls_status, name='handrive_api_hls_status'),
    path('handrive/api/hls/manifest', handrive_views.handrive_api_hls_manifest, name='handrive_api_hls_manifest'),
    path('handrive/api/hls/playlist', handrive_views.handrive_api_hls_playlist, name='handrive_api_hls_playlist'),
    path('handrive/api/hls/segment', handrive_views.handrive_api_hls_segment, name='handrive_api_hls_segment'),
    path('handrive/api/hls/poster', handrive_views.handrive_api_hls_poster, name='handrive_api_hls_poster'),
    path('handrive/api/hls/faststart', handrive_views.handrive_api_hls_faststart, name='handrive_api_hls_faststart'),
    path('handrive/api/hls/sprite', handrive_views.handrive_api_hls_sprite, name='handrive_api_hls_sprite'),
    path('handrive/api/hls/thumbnail-vtt', handrive_views.handrive_api_hls_thumbnail_vtt, name='handrive_api_hls_thumbnail_vtt'),
    path('handrive/api/vtt', handrive_views.handrive_api_vtt, name='handrive_api_vtt'),
    path('handrive/api/pdf-preview', handrive_views.handrive_api_pdf_preview, name='handrive_api_pdf_preview'),
    path('handrive/api/acl', handrive_views.handrive_api_acl, name='handrive_api_acl'),
    path('handrive/api/acl-options', handrive_views.handrive_api_acl_options, name='handrive_api_acl_options'),
    path('handrive/api/url-share', handrive_views.handrive_api_url_share, name='handrive_api_url_share'),
    path('handrive/api/sync-settings', handrive_views.handrive_api_sync_settings, name='handrive_api_sync_settings'),
    path('handrive/api/map/create', handrive_views.handrive_api_map_create, name='handrive_api_map_create'),
    path('handrive/api/map/data', handrive_views.handrive_api_map_data, name='handrive_api_map_data'),
    path('handrive/api/map/data/save', handrive_views.handrive_api_map_data_save, name='handrive_api_map_data_save'),
    path('handrive/api/map/icon-upload', handrive_views.handrive_api_map_icon_upload, name='handrive_api_map_icon_upload'),
    path('handrive/api/map/icon-delete', handrive_views.handrive_api_map_icon_delete, name='handrive_api_map_icon_delete'),
    path('handrive/api/folder-icon', handrive_views.handrive_api_folder_icon_serve, name='handrive_api_folder_icon_serve'),
    path('handrive/api/folder-icon/', handrive_views.handrive_api_folder_icon_serve),
    path('handrive/api/folder-icon/upload', handrive_views.handrive_api_folder_icon_upload, name='handrive_api_folder_icon_upload'),
    path('handrive/api/folder-icon/delete', handrive_views.handrive_api_folder_icon_delete, name='handrive_api_folder_icon_delete'),
    path('handrive/api/map/image-upload', handrive_views.handrive_api_map_attachment_upload, name='handrive_api_map_attachment_upload'),
    path('handrive/api/map-image/', handrive_views.handrive_api_map_image, name='handrive_api_map_image'),
    path('handrive/api/login-captcha-status', handrive_views.handrive_api_login_captcha_status, name='handrive_api_login_captcha_status'),
    path('handrive/api/login-2fa/resend-code', handrive_views.handrive_api_login_2fa_resend_code, name='handrive_api_login_2fa_resend_code'),
    path('handrive/api/signup-2fa/send-code', handrive_views.handrive_api_signup_2fa_send_code, name='handrive_api_signup_2fa_send_code'),
    path('handrive/api/signup-2fa/verify-code', handrive_views.handrive_api_signup_2fa_verify_code, name='handrive_api_signup_2fa_verify_code'),
    path('handrive/share/<str:owner_username>/<str:share_slug>', views.redirect_to_language_prefixed_path, name='handrive_shared_view'),
    path('handrive/share/<str:owner_username>/<str:share_slug>/', views.redirect_to_language_prefixed_path),
    path('handrive/share/<str:owner_username>/<str:share_slug>/<path:shared_subpath>', views.redirect_to_language_prefixed_path, name='handrive_shared_view_child'),
    path('handrive/<path:folder_path>/list', views.redirect_to_language_prefixed_path, name='handrive_list'),
    path('handrive/<path:folder_path>/list/', views.redirect_to_language_prefixed_path),
    path('handrive/map-editor/<path:map_path>', views.redirect_to_language_prefixed_path, name='handrive_map_editor'),
    path('handrive/map-viewer/<path:map_path>', views.redirect_to_language_prefixed_path, name='handrive_map_viewer'),
    path('handrive/api/image-editor/save', handrive_views.handrive_api_image_editor_save, name='handrive_api_image_editor_save'),
    path('handrive/api/image-editor/remove-background', handrive_views.handrive_api_image_editor_remove_background, name='handrive_api_image_editor_remove_background'),
    path('handrive/api/audio-editor/save', handrive_views.handrive_api_audio_editor_save, name='handrive_api_audio_editor_save'),
    path('handrive/api/video-editor/save', handrive_views.handrive_api_video_editor_save, name='handrive_api_video_editor_save'),
    path('handrive/api/pdf-editor/meta', handrive_views.handrive_api_pdf_editor_meta, name='handrive_api_pdf_editor_meta'),
    path('handrive/api/pdf-editor/page', handrive_views.handrive_api_pdf_editor_page, name='handrive_api_pdf_editor_page'),
    path('handrive/api/pdf-editor/save', handrive_views.handrive_api_pdf_editor_save, name='handrive_api_pdf_editor_save'),
    path('handrive/<path:doc_path>', views.redirect_to_language_prefixed_path, name='handrive_view'),
    re_path(r'^(?P<ui_lang>ko|en)/handrive/?$', handrive_views.handrive_root, name='handrive_root_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/handrive/list/?$', handrive_views.handrive_root, name='handrive_list_root_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/handrive/write/?$', handrive_views.handrive_write, name='handrive_write_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/signup/?$', handrive_views.handrive_signup, name='handrive_signup_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/login/?$', handrive_views.handrive_login, name='handrive_login_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/auth/github/start/?$', handrive_views.handrive_github_auth_start, name='handrive_github_auth_start_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/auth/google/start/?$', handrive_views.handrive_google_auth_start, name='handrive_google_auth_start_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/logout/?$', handrive_views.handrive_logout, name='handrive_logout_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/2fa-verify/?$', handrive_views.handrive_2fa_verify, name='handrive_2fa_verify_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/register-email/?$', handrive_views.handrive_register_email, name='handrive_register_email_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/privacy/?$', views.privacy_page, name='privacy_page_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/terms/?$', views.terms_page, name='terms_page_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/licenses/?$', views.licenses_page, name='licenses_page_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/handrive/cli/?$', views.hanharness_page, name='hanharness_page_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/handrive/cli/download/macos/?$', views.hanharness_download, name='hanharness_download_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/handrive/cli/download/windows/?$', views.hanharness_download_windows, name='hanharness_download_windows_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/handrive/ops/apply-static/?$', handrive_views.handrive_ops_apply_static, name='handrive_ops_apply_static_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/handrive/share/(?P<owner_username>[^/]+)/(?P<share_slug>[^/]+)/?$', handrive_views.handrive_shared_view, name='handrive_shared_view_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/handrive/share/(?P<owner_username>[^/]+)/(?P<share_slug>[^/]+)/(?P<shared_subpath>.+)/?$', handrive_views.handrive_shared_view, name='handrive_shared_view_child_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/handrive/(?P<folder_path>.+)/list/?$', handrive_views.handrive_list, name='handrive_list_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/handrive/map-editor/(?P<map_path>.+)/?$', handrive_views.handrive_map_editor, name='handrive_map_editor_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/handrive/map-viewer/(?P<map_path>.+)/?$', handrive_views.handrive_map_viewer, name='handrive_map_viewer_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/handrive/api/image-editor/save$', handrive_views.handrive_api_image_editor_save, name='handrive_api_image_editor_save_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/handrive/api/image-editor/remove-background$', handrive_views.handrive_api_image_editor_remove_background, name='handrive_api_image_editor_remove_background_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/handrive/api/pdf-editor/meta$', handrive_views.handrive_api_pdf_editor_meta, name='handrive_api_pdf_editor_meta_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/handrive/api/pdf-editor/page$', handrive_views.handrive_api_pdf_editor_page, name='handrive_api_pdf_editor_page_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/handrive/api/pdf-editor/save$', handrive_views.handrive_api_pdf_editor_save, name='handrive_api_pdf_editor_save_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/handrive/(?P<doc_path>.+)/?$', handrive_views.handrive_view, name='handrive_view_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/$', views.none, name='none_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/portfolio/$', views.portfolio_root_redirect, name='main_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/portfolio/write/?$', views.portfolio_write, name='portfolio_write_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/portfolio/(?P<user_id>[A-Za-z0-9_.-]+)/(?P<company_slug>[^/]+)/?$', views.portfolio_user_cover_letter, name='portfolio_user_cover_letter_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/portfolio/(?P<user_id>[A-Za-z0-9_.-]+)/$', views.portfolio_user, name='portfolio_user_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/project/(?P<project_id>\d+)/$', views.ProjectDetail, name='ProjectDetail_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/project/sample/(?P<sample_id>\d+)/$', views.DummyProjectDetail, name='DummyProjectDetail_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/project/(?P<user_id>[A-Za-z0-9_.-]+)/(?P<project_number>\d+)/$', views.ProjectDetailByUser, name='ProjectDetail_user_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/Salvations_Edge_4/$', views.Salvations_Edge_4, name='Salvations_Edge_4_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/Stratagem_Hero/$', views.Stratagem_Hero_page, name='Stratagem_Hero_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/Stratagem_Hero/Scoreboard/$', views.Stratagem_Hero_Scoreboard_page, name='Stratagem_Hero_Scoreboard_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/?$', views.sub_page, name='sub_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/bubble/?$', views.bubble_page, name='bubble_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/text-speaki/?$', views.text_bubble_page, name='text_bubble_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/image-pip-demo/sample-image\.png$', views.image_pip_demo_sample_image, name='image_pip_demo_sample_image_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/image-pip-demo/?$', views.image_pip_demo_page, name='image_pip_demo_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/image-color-picker/?$', views.image_color_picker_page, name='image_color_picker_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/image-color-picker/fetch-url/?$', views.image_color_picker_fetch_url, name='image_color_picker_fetch_url_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/video-to-gif/?$', views.video_to_gif_page, name='video_to_gif_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/video-to-gif/metadata/?$', views.video_to_gif_metadata, name='video_to_gif_metadata_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/video-to-gif/convert/?$', views.video_to_gif_convert, name='video_to_gif_convert_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/videotogif/?$', views.video_to_gif_legacy_redirect, name='video_to_gif_legacy_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/videotogif/metadata/?$', views.video_to_gif_metadata, name='video_to_gif_metadata_legacy_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/videotogif/convert/?$', views.video_to_gif_convert, name='video_to_gif_convert_legacy_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/network-info/?$', views.network_environment_page, name='network_environment_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/network-info/api/environment/?$', views.network_environment_api, name='network_environment_api_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/network-info/api/reverse-geocode/?$', views.network_reverse_geocode_api, name='network_reverse_geocode_api_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/qrbarcode/?$', views.qrbarcode_page, name='qrbarcode_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/qrbarcode/generate/?$', views.qrbarcode_generate, name='qrbarcode_generate_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/youtube-downloader/?$', views.youtube_downloader_page, name='youtube_downloader_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/youtube-downloader/formats/?$', views.youtube_formats, name='youtube_formats_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/youtube-downloader/download/?$', views.youtube_download, name='youtube_download_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/youtube-downloader/file/(?P<token>[0-9a-f]{32})/?$', views.youtube_download_file, name='youtube_download_file_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/youtube-downloader/save/?$', views.youtube_save_to_handrive, name='youtube_save_to_handrive_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/bumpercar-spiky/admin/?$', views.bumpercar_spiky_admin_page, name='bumpercar_spiky_admin_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/bumpercar-spiky/set-npc-health/?$', views.bumpercar_spiky_set_npc_health, name='bumpercar_spiky_set_npc_health_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/bumpercar-spiky/restart-server/?$', views.bumpercar_spiky_restart_server, name='bumpercar_spiky_restart_server_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/bumpercar-spiky/?$', views.hanplanet_multiplayer_page, name='bumpercar_spiky_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/raise-speaki/?$', views.raise_speaki_page, name='raise_speaki_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sub/Stratagem_Hero/add_score/$', views.add_score, name='add_score_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/comment/create/(?P<project_id>\d+)/$', views.ProjectComment_create, name='ProjectComment_create_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/root-shortcuts/$', views.root_shortcuts, name='root_shortcuts_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/root-shortcuts/reorder/$', views.root_shortcuts_reorder, name='root_shortcuts_reorder_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/root-shortcuts/(?P<shortcut_id>\d+)/$', views.root_shortcuts_detail, name='root_shortcuts_detail_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/theme-preference/$', views.theme_preference, name='theme_preference_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/user-preferences/$', views.user_preferences, name='user_preferences_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/wargame/session/$', views.wargame_session, name='wargame_session_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/wargame/navbar/$', views.wargame_navbar, name='wargame_navbar_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/wargame/solves/$', views.wargame_solves, name='wargame_solves_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/wargame/preferences/$', views.wargame_preferences, name='wargame_preferences_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/game-auth-token/$', views.game_auth_token, name='game_auth_token_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/map-collab-auth-token/$', views.map_collab_auth_token, name='map_collab_auth_token_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/account/profile-image/?$', views.account_profile_image_upload, name='account_profile_image_upload_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/chat/$', views.chat_with_ai, name='chat_with_ai_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/api/translate/$', views.translate_text, name='translate_text_lang'),
    path('portfolio/', views.redirect_to_language_prefixed_path, name='main'),
    path('portfolio/write', views.redirect_to_language_prefixed_path, name='portfolio_write_no_slash'),
    path('portfolio/write/', views.redirect_to_language_prefixed_path, name='portfolio_write'),
    path('portfolio/<str:user_id>/<path:company_slug>', views.redirect_to_language_prefixed_path, name='portfolio_user_cover_letter_no_slash'),
    path('portfolio/<str:user_id>/<path:company_slug>/', views.redirect_to_language_prefixed_path, name='portfolio_user_cover_letter'),
    path('portfolio/<str:user_id>/', views.redirect_to_language_prefixed_path, name='portfolio_user'),
    path('project/<int:project_id>/', views.redirect_to_language_prefixed_path, name='ProjectDetail'),
    path('project/<str:user_id>/<int:project_number>/', views.redirect_to_language_prefixed_path, name='ProjectDetail_user'),
    path('project/sample/<int:sample_id>/', views.redirect_to_language_prefixed_path, name='DummyProjectDetail'),
    path('sub/Salvations_Edge_4/', views.redirect_to_language_prefixed_path, name='Salvations_Edge_4'),
    path('sub/Stratagem_Hero/', views.redirect_to_language_prefixed_path, name='Stratagem_Hero'),
    path('sub/Stratagem_Hero/Scoreboard/', views.redirect_to_language_prefixed_path, name='Stratagem_Hero_Scoreboard'),
    path('sub/bubble', views.redirect_to_language_prefixed_path, name='bubble_no_slash'),
    path('sub/bubble/', views.redirect_to_language_prefixed_path, name='bubble'),
    path('sub/text-speaki', views.redirect_to_language_prefixed_path, name='text_bubble_no_slash'),
    path('sub/text-speaki/', views.redirect_to_language_prefixed_path, name='text_bubble'),
    path('sub/image-pip-demo/sample-image.png', views.image_pip_demo_sample_image, name='image_pip_demo_sample_image'),
    path('sub/image-pip-demo', views.redirect_to_language_prefixed_path, name='image_pip_demo_no_slash'),
    path('sub/image-pip-demo/', views.redirect_to_language_prefixed_path, name='image_pip_demo'),
    path('sub/image-color-picker', views.redirect_to_language_prefixed_path, name='image_color_picker_no_slash'),
    path('sub/image-color-picker/', views.redirect_to_language_prefixed_path, name='image_color_picker'),
    path('sub/image-color-picker/fetch-url/', views.image_color_picker_fetch_url, name='image_color_picker_fetch_url'),
    path('sub/video-to-gif', views.redirect_to_language_prefixed_path, name='video_to_gif_no_slash'),
    path('sub/video-to-gif/', views.redirect_to_language_prefixed_path, name='video_to_gif'),
    path('sub/video-to-gif/metadata/', views.video_to_gif_metadata, name='video_to_gif_metadata'),
    path('sub/video-to-gif/convert/', views.video_to_gif_convert, name='video_to_gif_convert'),
    path('sub/videotogif', views.video_to_gif_legacy_redirect, name='video_to_gif_legacy_no_slash'),
    path('sub/videotogif/', views.video_to_gif_legacy_redirect, name='video_to_gif_legacy'),
    path('sub/videotogif/metadata/', views.video_to_gif_metadata, name='video_to_gif_metadata_legacy'),
    path('sub/videotogif/convert/', views.video_to_gif_convert, name='video_to_gif_convert_legacy'),
    path('sub/network-info', views.redirect_to_language_prefixed_path, name='network_environment_no_slash'),
    path('sub/network-info/', views.redirect_to_language_prefixed_path, name='network_environment'),
    path('sub/network-info/api/environment/', views.network_environment_api, name='network_environment_api'),
    path('sub/network-info/api/reverse-geocode/', views.network_reverse_geocode_api, name='network_reverse_geocode_api'),
    path('sub/qrbarcode', views.redirect_to_language_prefixed_path, name='qrbarcode_no_slash'),
    path('sub/qrbarcode/', views.redirect_to_language_prefixed_path, name='qrbarcode'),
    path('sub/qrbarcode/generate/', views.qrbarcode_generate, name='qrbarcode_generate'),
    path('sub/youtube-downloader', views.redirect_to_language_prefixed_path, name='youtube_downloader_no_slash'),
    path('sub/youtube-downloader/', views.redirect_to_language_prefixed_path, name='youtube_downloader'),
    path('sub/youtube-downloader/formats/', views.youtube_formats, name='youtube_formats'),
    path('sub/youtube-downloader/download/', views.youtube_download, name='youtube_download'),
    re_path(r'^sub/youtube-downloader/file/(?P<token>[0-9a-f]{32})/?$', views.youtube_download_file, name='youtube_download_file'),
    path('sub/youtube-downloader/save/', views.youtube_save_to_handrive, name='youtube_save_to_handrive'),
    path('api/nyt-article/', views.nyt_article_api, name='nyt_article_api'),
    path('sub/bumpercar-spiky', views.redirect_to_language_prefixed_path, name='bumpercar_spiky_no_slash'),
    path('sub/bumpercar-spiky/admin', views.redirect_to_language_prefixed_path, name='bumpercar_spiky_admin_no_slash'),
    path('sub/bumpercar-spiky/admin/', views.redirect_to_language_prefixed_path, name='bumpercar_spiky_admin'),
    path('sub/bumpercar-spiky/', views.redirect_to_language_prefixed_path, name='bumpercar_spiky'),
    path('sub/raise-speaki', views.redirect_to_language_prefixed_path, name='raise_speaki_no_slash'),
    path('sub/raise-speaki/', views.redirect_to_language_prefixed_path, name='raise_speaki'),
    path('sub/Stratagem_Hero/add_score/', views.redirect_to_language_prefixed_path, name='add_score'),
    path('sub', views.redirect_to_language_prefixed_path, name='sub_no_slash'),
    path('sub/', views.redirect_to_language_prefixed_path, name='sub'),
    path('comment/create/<int:project_id>/', views.ProjectComment_create, name='ProjectComment_create'),
    path('api/root-shortcuts/', views.root_shortcuts, name='root_shortcuts'),
    path('api/root-shortcuts/reorder/', views.root_shortcuts_reorder, name='root_shortcuts_reorder'),
    path('api/root-shortcuts/<int:shortcut_id>/', views.root_shortcuts_detail, name='root_shortcuts_detail'),
    path('api/theme-preference/', views.theme_preference, name='theme_preference'),
    path('api/user-preferences/', views.user_preferences, name='user_preferences'),
    path('api/wargame/session/', views.wargame_session, name='wargame_session'),
    path('api/wargame/navbar/', views.wargame_navbar, name='wargame_navbar'),
    path('api/wargame/solves/', views.wargame_solves, name='wargame_solves'),
    path('api/wargame/preferences/', views.wargame_preferences, name='wargame_preferences'),
    path('api/game-auth-token/', views.game_auth_token, name='game_auth_token'),
    path('api/map-collab-auth-token/', views.map_collab_auth_token, name='map_collab_auth_token'),
    path('api/map-collab-presence/', views.map_collab_presence, name='map_collab_presence'),
    path('api/internal/bumpercar-spiky/stats/', views.bumpercar_spiky_stats_record, name='bumpercar_spiky_stats_record'),
    path('account/profile-image/', views.account_profile_image_upload, name='account_profile_image_upload'),
    path('api/chat/', views.chat_with_ai, name='chat_with_ai'),
    path('api/translate/', views.translate_text, name='translate_text'),
    path('api/git/repos/', views.git_repo_create, name='git_repo_create'),
    path('api/git/repos/by-path/', views.git_repo_by_path, name='git_repo_by_path'),
    path('api/git/repos/<int:repo_id>/collaborators/', views.git_repo_collaborator, name='git_repo_collaborator'),
    path('api/git/repos/<int:repo_id>/clone/', views.git_repo_clone_url, name='git_repo_clone_url'),
    path('api/git/repos/<int:repo_id>/status/', views.git_repo_status, name='git_repo_status'),
    path('api/git/repos/<int:repo_id>/retry/', views.git_repo_retry, name='git_repo_retry'),
    path('api/git/repos/<str:repo_id>/branches/', views.git_branch_create, name='git_branch_create'),
    path('api/git/repos/<str:repo_id>/branches/delete/', views.git_branch_delete, name='git_branch_delete'),
    # Git Device Flow 인증
    path('api/git/auth/device/',  views.git_auth_device,  name='git_auth_device'),
    path('api/git/auth/token/',   views.git_auth_token,   name='git_auth_token'),
    path('api/git/auth/approve/', views.git_auth_approve, name='git_auth_approve'),
    path('git-auth/',             views.git_auth_page,    name='git_auth_page'),
    path('git-auth/credential-helper/', views.git_credential_helper_download, name='git_credential_helper_download'),
    path('sync-client/handrive.exe', views.handrive_sync_client_download, name='handrive_sync_client_download'),
    # Gitea SSO 릴레이: 로그인 후 Gitea 자동 로그인
    path('sso/gitea', handrive_views.handrive_gitea_sso_relay, name='gitea_sso_relay'),
    path('logout/bridge', handrive_views.handrive_logout_bridge, name='handrive_logout_bridge'),
    re_path(r'^(?P<ui_lang>ko|en)/logout/bridge/?$', handrive_views.handrive_logout_bridge, name='handrive_logout_bridge_lang'),
    re_path(r'^(?P<ui_lang>ko|en)/sync-client/handrive\.exe/?$', views.handrive_sync_client_download, name='handrive_sync_client_download_lang'),
]
