# Generated by Django 4.2.24 on 2026-06-01 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('git', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubAccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_user_id', models.BigIntegerField(unique=True)),
                ('github_login', models.CharField(max_length=255)),
                ('github_name', models.CharField(blank=True, default='', max_length=255)),
                ('github_email', models.EmailField(blank=True, default='', max_length=254)),
                ('github_avatar_url', models.URLField(blank=True, default='', max_length=1024)),
                ('user_access_token', models.TextField(blank=True, default='')),
                ('user_access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('user_refresh_token', models.TextField(blank=True, default='')),
                ('user_refresh_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('token_scope', models.CharField(blank=True, default='', max_length=512)),
                ('token_type', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_githubaccountmapping',
                'indexes': [models.Index(fields=['github_login'], name='main_github_github__f3b63c_idx'), models.Index(fields=['user', 'updated_at'], name='main_github_user_id_fc12f0_idx')],
            },
        ),
    ]
