# Generated by Django 4.2.24 on 2026-06-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0002_githubaccountmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubaccountmapping',
            name='selected_repositories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
