# Generated by Codex on 2026-06-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("git", "0004_googleaccountmapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="googleaccountmapping",
            name="google_drive_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
