ServerRoot "/usr"
PidFile "/Users/imhanbyeol/Development/Hanplanet/Wargame/data/apache.pid"
Mutex file:/Users/imhanbyeol/Development/Hanplanet/Wargame/data
Listen 8090
ServerName wargame.hanplanet.com
ServerSignature Off
ServerTokens Prod

LoadModule mpm_prefork_module libexec/apache2/mod_mpm_prefork.so
LoadModule authz_core_module libexec/apache2/mod_authz_core.so
LoadModule authz_host_module libexec/apache2/mod_authz_host.so
LoadModule unixd_module libexec/apache2/mod_unixd.so
LoadModule dir_module libexec/apache2/mod_dir.so
LoadModule log_config_module libexec/apache2/mod_log_config.so
LoadModule mime_module libexec/apache2/mod_mime.so
LoadModule headers_module libexec/apache2/mod_headers.so
LoadModule proxy_module libexec/apache2/mod_proxy.so
LoadModule proxy_fcgi_module libexec/apache2/mod_proxy_fcgi.so

TypesConfig "/etc/apache2/mime.types"

ErrorLog "/Users/imhanbyeol/Development/Hanplanet/Wargame/data/apache-error.log"
CustomLog "/Users/imhanbyeol/Development/Hanplanet/Wargame/data/apache-access.log" combined

DocumentRoot "/Users/imhanbyeol/Development/Hanplanet/Wargame/public"
DirectoryIndex index.php

<Directory />
    AllowOverride None
    Require all denied
</Directory>

<Directory "/Users/imhanbyeol/Development/Hanplanet/Wargame/public">
    Options -Indexes -Includes -ExecCGI
    AllowOverride None
    Require all granted
</Directory>

<FilesMatch "^\.">
    Require all denied
</FilesMatch>

<FilesMatch "\.php$">
    SetHandler "proxy:fcgi://127.0.0.1:9000"
</FilesMatch>

Header always set X-Content-Type-Options "nosniff"
Header always set Referrer-Policy "no-referrer"
