ServerRoot "/usr"
PidFile "/Users/imhanbyeol/Development/Hanplanet/Wargame/data/apache.pid"
Mutex file:/Users/imhanbyeol/Development/Hanplanet/Wargame/data
ServerName wargame.hanplanet.com

LoadModule mpm_prefork_module libexec/apache2/mod_mpm_prefork.so
LoadModule authz_core_module libexec/apache2/mod_authz_core.so
LoadModule authz_host_module libexec/apache2/mod_authz_host.so
LoadModule unixd_module libexec/apache2/mod_unixd.so
LoadModule dir_module libexec/apache2/mod_dir.so
LoadModule log_config_module libexec/apache2/mod_log_config.so
LoadModule mime_module libexec/apache2/mod_mime.so
LoadModule headers_module libexec/apache2/mod_headers.so
LoadModule rewrite_module libexec/apache2/mod_rewrite.so
LoadModule proxy_module libexec/apache2/mod_proxy.so
LoadModule proxy_fcgi_module libexec/apache2/mod_proxy_fcgi.so

TypesConfig "/etc/apache2/mime.types"
ErrorLog "/Users/imhanbyeol/Development/Hanplanet/Wargame/data/apache-error.log"

ServerTokens Prod
ServerSignature Off
TraceEnable Off

Include "/Users/imhanbyeol/Development/Hanplanet/Wargame/deploy/apache/wargame-vhost.conf"
