# Generated by Django 4.2.24 on 2026-03-24 00:26
# Edited: use SeparateDatabaseAndState for Docs*→Handrive* renames (tables already exist).

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0032_add_gitdevicecode'),
    ]

    operations = [
        # Docs* → Handrive* 모델 리네임: DB 테이블은 이미 존재하므로 state만 업데이트
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='HandriveAccessRuleReadGroup',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ],
                    options={
                        'db_table': 'main_docsaccessrule_read_groups',
                        'managed': False,
                    },
                ),
                migrations.CreateModel(
                    name='HandriveAccessRuleReadUser',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ],
                    options={
                        'db_table': 'main_docsaccessrule_read_users',
                        'managed': False,
                    },
                ),
                migrations.CreateModel(
                    name='HandriveAccessRuleWriteGroup',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ],
                    options={
                        'db_table': 'main_docsaccessrule_write_groups',
                        'managed': False,
                    },
                ),
                migrations.CreateModel(
                    name='HandriveAccessRuleWriteUser',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ],
                    options={
                        'db_table': 'main_docsaccessrule_write_users',
                        'managed': False,
                    },
                ),
                migrations.CreateModel(
                    name='HandriveAccessRule',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('path', models.CharField(blank=True, default='', help_text='/handrive 기준 상대 경로. 비우면 /handrive 루트', max_length=1024, unique=True, verbose_name='경로')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                        ('read_groups', models.ManyToManyField(blank=True, related_name='handrive_read_access_rules', through='main.HandriveAccessRuleReadGroup', to='auth.group', verbose_name='읽기 허용 그룹')),
                        ('read_users', models.ManyToManyField(blank=True, related_name='handrive_read_access_rules', through='main.HandriveAccessRuleReadUser', to=settings.AUTH_USER_MODEL, verbose_name='읽기 허용 사용자')),
                        ('write_groups', models.ManyToManyField(blank=True, related_name='handrive_write_access_rules', through='main.HandriveAccessRuleWriteGroup', to='auth.group', verbose_name='쓰기 허용 그룹')),
                        ('write_users', models.ManyToManyField(blank=True, related_name='handrive_write_access_rules', through='main.HandriveAccessRuleWriteUser', to=settings.AUTH_USER_MODEL, verbose_name='쓰기 허용 사용자')),
                    ],
                    options={
                        'verbose_name': 'HanDrive 접근 규칙',
                        'verbose_name_plural': 'HanDrive 접근 규칙',
                        'db_table': 'main_docsaccessrule',
                        'ordering': ['path'],
                    },
                ),
                migrations.CreateModel(
                    name='HandriveLoginAttemptGuard',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('failed_attempts', models.PositiveIntegerField(default=0, verbose_name='연속 로그인 실패 횟수')),
                        ('captcha_required', models.BooleanField(default=False, verbose_name='캡챠 필요 여부')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handrive_login_attempt_guard', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                    ],
                    options={
                        'verbose_name': 'HanDrive 로그인 보호 상태',
                        'verbose_name_plural': 'HanDrive 로그인 보호 상태',
                        'db_table': 'main_docsloginattemptguard',
                    },
                ),
                migrations.CreateModel(
                    name='HandriveSharedLink',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('path', models.CharField(help_text='/handrive 기준 상대 파일 경로', max_length=1024, unique=True, verbose_name='문서 경로')),
                        ('share_slug', models.CharField(max_length=255, verbose_name='공유 슬러그')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                        ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handrive_shared_links', to=settings.AUTH_USER_MODEL, verbose_name='공유 생성 사용자')),
                    ],
                    options={
                        'verbose_name': '문서 공유 링크',
                        'verbose_name_plural': '문서 공유 링크',
                        'db_table': 'main_docssharedlink',
                        'ordering': ['owner__username', 'share_slug'],
                    },
                ),
                migrations.RemoveField(
                    model_name='docsloginattemptguard',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='docssharedlink',
                    name='owner',
                ),
                migrations.DeleteModel(
                    name='DocsAccessRule',
                ),
                migrations.DeleteModel(
                    name='DocsLoginAttemptGuard',
                ),
                migrations.DeleteModel(
                    name='DocsSharedLink',
                ),
                migrations.AddConstraint(
                    model_name='handrivesharedlink',
                    constraint=models.UniqueConstraint(fields=('owner', 'share_slug'), name='unique_docs_shared_link_owner_slug'),
                ),
            ],
            database_operations=[
                # 테이블 및 제약조건이 DB에 이미 존재하므로 DB 작업 없음
            ],
        ),
        # HandriveUserQuota는 신규 테이블이므로 실제 CREATE TABLE 실행
        migrations.CreateModel(
            name='HandriveUserQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_bytes', models.BigIntegerField(help_text='사용자별 최대 저장 용량. 예: 1GB = 1073741824, 5GB = 5368709120', verbose_name='저장 용량 (bytes)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handrive_quota', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'HanDrive 사용자 저장 용량',
                'verbose_name_plural': 'HanDrive 사용자 저장 용량',
            },
        ),
    ]
