# Generated by Django 4.2.24 on 2026-03-26 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0034_remove_moved_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncUploadSession',
            fields=[
                ('upload_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('file_id', models.UUIDField(help_text='업로드 대상 SyncFile.id')),
                ('path', models.TextField()),
                ('size', models.BigIntegerField()),
                ('hash', models.CharField(max_length=64)),
                ('storage_key', models.TextField()),
                ('created_at', models.BigIntegerField(help_text='서버 Unix timestamp (ms)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync 업로드 세션',
                'verbose_name_plural': 'Sync 업로드 세션',
            },
        ),
        migrations.CreateModel(
            name='SyncFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.TextField(help_text='사용자 기준 상대 경로 (예: /docs/a.txt)')),
                ('size', models.BigIntegerField()),
                ('hash', models.CharField(help_text='SHA-256 hex digest', max_length=64)),
                ('version', models.BigIntegerField(default=1, help_text='단조 증가 버전 (충돌 판단 기준)')),
                ('storage_key', models.TextField(help_text='MinIO 오브젝트 키: {user_id}/{file_id}')),
                ('client_modified_at', models.BigIntegerField(help_text='클라이언트 제공 수정 시각 (ms, 참고용)')),
                ('server_modified_at', models.BigIntegerField(help_text='서버 기준 수정 시각 (ms, sync 판단 기준)')),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync 파일',
                'verbose_name_plural': 'Sync 파일',
                'indexes': [models.Index(fields=['user', 'hash'], name='main_syncfi_user_id_9e5d45_idx')],
                'unique_together': {('user', 'path')},
            },
        ),
        migrations.CreateModel(
            name='SyncChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.UUIDField(help_text='SyncFile.id (삭제 후에도 이력 유지를 위해 FK 미사용)')),
                ('path', models.TextField(help_text='변경 시점의 파일 경로')),
                ('old_path', models.TextField(blank=True, help_text='MOVE 시 이전 경로', null=True)),
                ('type', models.CharField(choices=[('CREATE', '생성'), ('UPDATE', '수정'), ('DELETE', '삭제'), ('MOVE', '이동/이름변경')], max_length=10)),
                ('version', models.BigIntegerField(help_text='변경 후 버전')),
                ('created_at', models.BigIntegerField(help_text='서버 Unix timestamp (ms)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync 변경 이력',
                'verbose_name_plural': 'Sync 변경 이력',
                'indexes': [models.Index(fields=['user', 'created_at'], name='main_syncch_user_id_85874c_idx')],
            },
        ),
    ]
