# Generated by Django 4.2.24 on 2026-04-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_userprofile_sync_excluded_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='session_token',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='세션 토큰'),
        ),
    ]
