# Generated by Django 4.2.24 on 2026-04-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_add_session_token_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='handriveuserquota',
            name='hanharness_enabled',
            field=models.BooleanField(default=False, help_text='활성화하면 이 사용자가 HanHarness를 통해 AI API를 사용할 수 있습니다.', verbose_name='HanHarness 사용 허용'),
        ),
        migrations.AddField(
            model_name='handriveuserquota',
            name='hanharness_token_limit_5h',
            field=models.PositiveIntegerField(default=0, help_text='최근 5시간 내 사용 가능한 최대 토큰 수. 0이면 무제한.', verbose_name='5시간 토큰 제한'),
        ),
    ]
