# Generated by Django 4.2.24 on 2026-04-17 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_handriveuserquota_hanharness_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handriveuserquota',
            options={'verbose_name': 'HanDrive 사용자 저장 용량/CLI 사용량', 'verbose_name_plural': 'HanDrive 사용자 저장 용량/CLI 사용량'},
        ),
    ]
