# Generated by Django 4.2.24 on 2026-04-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_handriveuserquota_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='handriveuserquota',
            name='scoped_entry_limit',
            field=models.PositiveIntegerField(default=0, help_text='개인 폴더에 허용되는 최대 파일/폴더 수. 0이면 기본값(100개) 적용.', verbose_name='파일/폴더 개수 제한'),
        ),
    ]
