# Generated by Django 4.2.24 on 2026-04-30 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0040_handriveuserquota_scoped_entry_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handriveuserquota',
            name='scoped_entry_limit',
            field=models.PositiveIntegerField(default=0, help_text='개인 폴더에 허용되는 최대 파일/폴더 수. 0이면 무제한. 설정 없으면 기본값(100개) 적용.', verbose_name='파일/폴더 개수 제한'),
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=64, unique=True, verbose_name='디바이스 토큰')),
                ('last_seen_at', models.DateTimeField(verbose_name='마지막 확인일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '신뢰된 기기',
                'verbose_name_plural': '신뢰된 기기',
                'indexes': [models.Index(fields=['user', 'last_seen_at'], name='main_truste_user_id_dd6167_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name='인증 코드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('expires_at', models.DateTimeField(verbose_name='만료일')),
                ('used', models.BooleanField(default=False, verbose_name='사용됨')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_codes', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '이메일 인증 코드',
                'verbose_name_plural': '이메일 인증 코드',
                'indexes': [models.Index(fields=['user', 'created_at'], name='main_emailv_user_id_d0087e_idx')],
            },
        ),
    ]
