# Generated by Django 4.2.24 on 2026-05-22 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0041_emailverificationcode_trusteddevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='WargameSolve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.CharField(max_length=80, verbose_name='문제 ID')),
                ('solved_at', models.DateTimeField(auto_now_add=True, verbose_name='해결일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wargame_solves', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '워게임 해결 기록',
                'verbose_name_plural': '워게임 해결 기록',
                'indexes': [models.Index(fields=['user', 'challenge_id'], name='main_wargam_user_id_0cbbb7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='wargamesolve',
            constraint=models.UniqueConstraint(fields=('user', 'challenge_id'), name='unique_wargame_solve_user_challenge'),
        ),
    ]
