# Generated by Django 4.2.24 on 2026-06-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_emailtwofactorbypassuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='weather_city',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='날씨 도시'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weather_country',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='날씨 국가'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weather_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='날씨 위도'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weather_location_source',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='날씨 위치 출처'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weather_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='날씨 경도'),
        ),
    ]
