# Generated by Codex on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0046_userprofile_weather_city_userprofile_weather_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="weather_location_label",
            field=models.CharField(blank=True, default="", max_length=180, verbose_name="날씨 위치 표시명"),
        ),
    ]
