# Generated by Django 4.2.24 on 2026-06-28 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0048_onscripteraccessuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinecraftLinkCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, unique=True, verbose_name='코드 해시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('expires_at', models.DateTimeField(verbose_name='만료일')),
                ('used', models.BooleanField(default=False, verbose_name='사용됨')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='사용일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minecraft_link_codes', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'Minecraft 연동 코드',
                'verbose_name_plural': 'Minecraft 연동 코드',
                'db_table': 'main_minecraftlinkcode',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'expires_at'], name='main_minecr_user_id_a694df_idx'), models.Index(fields=['used', 'expires_at'], name='main_minecr_used_f59208_idx')],
            },
        ),
        migrations.CreateModel(
            name='MinecraftAccountLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minecraft_uuid', models.CharField(max_length=36, unique=True, verbose_name='Minecraft UUID')),
                ('minecraft_name', models.CharField(max_length=32, verbose_name='Minecraft 닉네임')),
                ('edition', models.CharField(choices=[('java', 'Java Edition'), ('bedrock', 'Bedrock Edition'), ('unknown', 'Unknown')], default='unknown', max_length=12, verbose_name='에디션')),
                ('floodgate_xuid', models.CharField(blank=True, default='', max_length=32, verbose_name='Floodgate XUID')),
                ('first_linked_at', models.DateTimeField(auto_now_add=True, verbose_name='최초 연동일')),
                ('last_linked_at', models.DateTimeField(auto_now=True, verbose_name='최근 연동일')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 확인일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minecraft_account_links', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'Minecraft 계정 연동',
                'verbose_name_plural': 'Minecraft 계정 연동',
                'db_table': 'main_minecraftaccountlink',
                'ordering': ['user__username', 'minecraft_name'],
                'indexes': [models.Index(fields=['user', 'edition'], name='main_minecr_user_id_aa1bb1_idx'), models.Index(fields=['minecraft_name'], name='main_minecr_minecra_ab3f9e_idx'), models.Index(fields=['floodgate_xuid'], name='main_minecr_floodga_0006cd_idx')],
            },
        ),
    ]
