# Generated by Django 4.2.24 on 2026-06-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_minecraftlinkcode_minecraftaccountlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='force_password_change',
            field=models.BooleanField(default=False, verbose_name='비밀번호 변경 필요'),
        ),
    ]
