# Generated by Django 4.2.24 on 2026-07-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_remove_userprofile_handrive_tutorial_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handriveuserquota',
            name='quota_bytes',
            field=models.BigIntegerField(default=53687091200, help_text='사용자별 최대 저장 용량. 예: 50GB = 53687091200', verbose_name='저장 용량 (bytes)'),
        ),
    ]
