# Generated by Django 4.2.24 on 2026-07-03 16:42

import django.core.validators
from django.db import migrations, models


def create_default_handrive_site_settings(apps, schema_editor):
    HandriveSiteSettings = apps.get_model('main', 'HandriveSiteSettings')
    HandriveSiteSettings.objects.get_or_create(
        singleton_key=1,
        defaults={'default_quota_bytes': 53687091200},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_alter_handriveuserquota_quota_bytes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandriveSiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('default_quota_bytes', models.BigIntegerField(default=53687091200, help_text='사용자별 저장 용량 설정이 없을 때 적용되는 기본 HanDrive 용량입니다.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='기본 저장 용량 (bytes)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': 'HanDrive 기본 설정',
                'verbose_name_plural': 'HanDrive 기본 설정',
            },
        ),
        migrations.RunPython(create_default_handrive_site_settings, migrations.RunPython.noop),
    ]
