# Generated by Django 5.0.1 on 2026-07-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0055_handrivesitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="handrivesharedlink",
            name="uses_opaque_tokens",
            field=models.BooleanField(default=False, verbose_name="난수 공유 경로 사용"),
        ),
        migrations.CreateModel(
            name="HandriveSharedPathToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("relative_path", models.CharField(max_length=1024, verbose_name="공유 루트 기준 상대 경로")),
                ("token", models.CharField(max_length=255, unique=True, verbose_name="난수 경로 토큰")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("shared_link", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="path_tokens", to="main.handrivesharedlink", verbose_name="공유 링크")),
            ],
            options={
                "verbose_name": "문서 공유 경로 토큰",
                "verbose_name_plural": "문서 공유 경로 토큰",
                "ordering": ["shared_link_id", "relative_path"],
            },
        ),
        migrations.AddConstraint(
            model_name="handrivesharedpathtoken",
            constraint=models.UniqueConstraint(fields=("shared_link", "relative_path"), name="unique_handrive_shared_link_relative_path"),
        ),
    ]
