# Generated by Django 4.2.24 on 2026-07-14 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_handrivesharedlink_opaque_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandriveEditorCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(help_text='예: .md, .py, .js', max_length=16, validators=[django.core.validators.RegexValidator(message='확장자는 .js처럼 점으로 시작하는 영문 소문자 형식이어야 합니다.', regex='^\\.[a-z0-9][a-z0-9_+-]*$')], verbose_name='파일 확장자')),
                ('trigger', models.CharField(max_length=80, verbose_name='트리거')),
                ('insert_text', models.TextField(verbose_name='삽입 내용')),
                ('label', models.CharField(blank=True, default='', max_length=200, verbose_name='표시명')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='설명')),
                ('kind', models.CharField(blank=True, default='', help_text='비워 두면 삽입 내용에 따라 자동 판별합니다.', max_length=24, verbose_name='종류')),
                ('cursor_back', models.PositiveIntegerField(default=0, help_text='마지막 어절까지 적용한 뒤 커서를 뒤로 이동할 문자 수입니다.', verbose_name='완료 후 커서 이동량')),
                ('priority', models.IntegerField(default=0, verbose_name='우선순위')),
                ('enabled', models.BooleanField(default=True, verbose_name='사용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': 'HanDrive 코드 자동완성',
                'verbose_name_plural': 'HanDrive 코드 자동완성',
                'ordering': ['extension', '-priority', 'trigger', 'id'],
                'indexes': [models.Index(fields=['enabled', 'extension', 'priority'], name='main_handri_enabled_c4dbc3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='handriveeditorcompletion',
            constraint=models.UniqueConstraint(fields=('extension', 'trigger'), name='unique_handrive_editor_completion_trigger'),
        ),
    ]
