# Generated by Django 4.2.24 on 2026-07-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_seed_handrive_editor_completions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BumpercarGameplaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='게임 설정')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '범퍼카 게임 설정',
                'verbose_name_plural': '범퍼카 게임 설정',
            },
        ),
        migrations.CreateModel(
            name='BumpercarSkin',
            fields=[
                ('name', models.SlugField(max_length=80, primary_key=True, serialize=False, verbose_name='스킨 키')),
                ('asset_source_name', models.SlugField(blank=True, default='', max_length=80, verbose_name='자산 소스 키')),
                ('fallback_sound_source_name', models.SlugField(blank=True, default='', max_length=80, verbose_name='대체 음원 소스 키')),
                ('preview_icon_name', models.CharField(default='main', max_length=80, verbose_name='대표 아이콘 이름')),
                ('skin_type', models.CharField(choices=[('classic', 'Classic'), ('double', 'Double'), ('many', 'Many'), ('pumkin', 'Pumkin'), ('evolution', 'Evolution')], default='classic', max_length=16, verbose_name='스킨 유형')),
                ('display_name_ko', models.CharField(max_length=120, verbose_name='한국어 이름')),
                ('display_name_en', models.CharField(max_length=120, verbose_name='영어 이름')),
                ('unlock_condition_ko', models.CharField(blank=True, default='', max_length=200, verbose_name='한국어 해금 조건')),
                ('unlock_condition_en', models.CharField(blank=True, default='', max_length=200, verbose_name='영어 해금 조건')),
                ('description_ko', models.TextField(blank=True, default='', verbose_name='한국어 설명')),
                ('description_en', models.TextField(blank=True, default='', verbose_name='영어 설명')),
                ('unlock_stat_key', models.CharField(blank=True, default='', max_length=80, verbose_name='해금 전적 키')),
                ('unlock_threshold', models.PositiveIntegerField(default=0, verbose_name='해금 기준값')),
                ('admin_only', models.BooleanField(default=False, verbose_name='관리자 전용')),
                ('disabled_game_slugs', models.JSONField(blank=True, default=list, verbose_name='비활성 게임 슬러그')),
                ('visual_scale', models.FloatField(default=1.0, verbose_name='표시 배율')),
                ('display_order', models.IntegerField(default=0, verbose_name='표시 순서')),
                ('enabled', models.BooleanField(default=True, verbose_name='사용')),
                ('asset_manifest', models.JSONField(blank=True, default=dict, verbose_name='자산 manifest')),
                ('manifest_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='manifest 수정일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '범퍼카 스킨',
                'verbose_name_plural': '범퍼카 스킨',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OnscripterGameConfig',
            fields=[
                ('slug', models.SlugField(max_length=80, primary_key=True, serialize=False, verbose_name='슬러그')),
                ('title', models.CharField(max_length=160, verbose_name='게임 제목')),
                ('folder_name', models.CharField(max_length=255, verbose_name='원본 폴더명')),
                ('asset_folder_name', models.CharField(max_length=255, verbose_name='웹 자산 폴더명')),
                ('description_ko', models.TextField(blank=True, default='', verbose_name='한국어 설명')),
                ('description_en', models.TextField(blank=True, default='', verbose_name='영어 설명')),
                ('thumbnail_path', models.CharField(blank=True, default='', max_length=512, verbose_name='대표 이미지 상대 경로')),
                ('encoding_arg', models.CharField(default='--enc:utf8', max_length=40, verbose_name='엔진 인코딩 인자')),
                ('width', models.PositiveIntegerField(default=800, verbose_name='화면 너비')),
                ('height', models.PositiveIntegerField(default=600, verbose_name='화면 높이')),
                ('meta_title', models.CharField(blank=True, default='', max_length=200, verbose_name='메타 제목')),
                ('direct_voice_playback', models.BooleanField(default=False, verbose_name='직접 음성 재생')),
                ('display_order', models.IntegerField(default=0, verbose_name='표시 순서')),
                ('enabled', models.BooleanField(default=True, verbose_name='사용')),
                ('asset_manifest', models.JSONField(blank=True, default=dict, verbose_name='자산 manifest')),
                ('manifest_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='manifest 수정일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': 'ONScripter 게임',
                'verbose_name_plural': 'ONScripter 게임',
                'ordering': ['display_order', 'slug'],
            },
        ),
    ]
