# Generated by Django 4.2.24 on 2026-07-21 04:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0060_seed_game_catalog_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinecraftTradeListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_minecraft_name', models.CharField(max_length=32, verbose_name='판매자 Minecraft 닉네임')),
                ('buyer_minecraft_name', models.CharField(blank=True, default='', max_length=32, verbose_name='구매자 Minecraft 닉네임')),
                ('sell_item', models.CharField(max_length=64, verbose_name='판매 아이템')),
                ('sell_amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='판매 수량')),
                ('price_item', models.CharField(max_length=64, verbose_name='대가 아이템')),
                ('price_amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='대가 수량')),
                ('status', models.CharField(choices=[('open', 'Open'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('claimed', 'Claimed')], default='open', max_length=12, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='거래 완료일')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='취소일')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='수령일')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minecraft_trade_purchases', to=settings.AUTH_USER_MODEL, verbose_name='구매자')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minecraft_trade_listings', to=settings.AUTH_USER_MODEL, verbose_name='판매자')),
            ],
            options={
                'verbose_name': 'Minecraft 거래글',
                'verbose_name_plural': 'Minecraft 거래글',
                'db_table': 'main_minecrafttradelisting',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='main_minecr_status_75d166_idx'), models.Index(fields=['seller', 'status'], name='main_minecr_seller__8187d9_idx'), models.Index(fields=['buyer', 'status'], name='main_minecr_buyer_i_c0c452_idx')],
            },
        ),
    ]
