# Generated by Django 4.2.24 on 2026-07-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_minecraft_trade_partial_fills'),
    ]

    operations = [
        migrations.AddField(
            model_name='minecrafttradelisting',
            name='sell_item_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='판매 아이템 상태'),
        ),
    ]
