# Generated by Django 4.2.24 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0063_minecraft_trade_item_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="minecrafttradelisting",
            name="is_npc",
            field=models.BooleanField(default=False, verbose_name="NPC 거래"),
        ),
    ]
