name: HanplanetTimber
version: 1.2.4
main: com.hanplanet.minecraft.timber.HanplanetTimberPlugin
api-version: "26.2"
description: Connected falling tree animation plugin for Hanplanet.
author: Hanplanet
permissions:
  hanplanettimber.use:
    description: Allows tree felling with HanplanetTimber.
    default: true
