"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import json
import mimetypes
import os
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from storage_profile import get_disc_mode, get_forgejo_repos_root, get_github_repo_cache_root, get_media_root

mimetypes.add_type("application/javascript", ".js", strict=True)
mimetypes.add_type("application/javascript", ".mjs", strict=True)
mimetypes.add_type("application/wasm", ".wasm", strict=True)
mimetypes.add_type("video/x-matroska", ".mkv", strict=True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default_csv):
    raw = os.environ.get(name, default_csv)
    return [item.strip() for item in raw.split(",") if item.strip()]


def env_cookie_domain(name, default=None):
    raw = os.environ.get(name)
    if raw is None:
        return default
    normalized = raw.strip()
    return normalized or None

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", default=False)
RUNNING_TESTS = "test" in sys.argv
DEFAULT_SECURE_TRANSPORT = not DEBUG and not RUNNING_TESTS

if DEBUG:
    INTERNAL_IPS = ["127.0.0.1", "::1"]


def load_secret_key():
    secret_key = load_env_or_file_secret("DJANGO_SECRET_KEY")
    if secret_key:
        return secret_key

    secrets_path = BASE_DIR / "config" / "secrets.json"
    if secrets_path.exists():
        try:
            with secrets_path.open("r", encoding="utf-8") as file:
                secrets = json.load(file)
        except (OSError, json.JSONDecodeError) as exc:
            raise ImproperlyConfigured(
                "config/secrets.json could not be parsed for SECRET_KEY."
            ) from exc

        secret_key = secrets.get("SECRET_KEY")
        if secret_key:
            return secret_key

    if DEBUG:
        return "local-development-only-secret-key-change-me-please-2026-rotate-this"

    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY (or config/secrets.json SECRET_KEY) is required when DEBUG is False."
    )


def load_env_or_file_secret(name):
    file_path = os.environ.get(f"{name}_FILE")
    if file_path:
        try:
            value = Path(file_path).read_text(encoding="utf-8").strip()
        except OSError:
            value = ""
        if value:
            return value

    value = os.environ.get(name)
    if value is not None and str(value).strip():
        return str(value).strip()
    return ""


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = load_secret_key()


def load_optional_secret(name, default=""):
    from_env = load_env_or_file_secret(name)
    if from_env:
        return from_env

    # 디버그 모드에서는 secrets.json 파일이 없어도 기본값 반환
    if DEBUG:
        return default

    secrets_path = BASE_DIR / "config" / "secrets.json"
    if secrets_path.exists():
        try:
            with secrets_path.open("r", encoding="utf-8") as file:
                secrets = json.load(file)
        except (OSError, json.JSONDecodeError):
            return default
        value = secrets.get(name)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return default


def load_optional_int_secret(name, default):
    from_env = load_env_or_file_secret(name)
    if from_env:
        try:
            return int(from_env)
        except ValueError:
            return default

    if DEBUG:
        return default

    secrets_path = BASE_DIR / "config" / "secrets.json"
    if secrets_path.exists():
        try:
            with secrets_path.open("r", encoding="utf-8") as file:
                secrets = json.load(file)
        except (OSError, json.JSONDecodeError):
            return default
        value = secrets.get(name)
        try:
            return int(value)
        except (TypeError, ValueError):
            return default
    return default


def load_optional_bool_secret(name, default=False):
    from_env = load_env_or_file_secret(name)
    if from_env:
        return from_env.lower() in {"1", "true", "yes", "on"}

    if DEBUG:
        return default

    secrets_path = BASE_DIR / "config" / "secrets.json"
    if secrets_path.exists():
        try:
            with secrets_path.open("r", encoding="utf-8") as file:
                secrets = json.load(file)
        except (OSError, json.JSONDecodeError):
            return default
        value = secrets.get(name)
        if isinstance(value, bool):
            return value
        if isinstance(value, str) and value.strip():
            return value.strip().lower() in {"1", "true", "yes", "on"}
    return default

# Ollama (local LLM) settings
# The model is injected by launchd/env so the app code does not hardcode it.
OLLAMA_BASE_URL = os.environ.get("OLLAMA_BASE_URL", "http://127.0.0.1:11434")
OLLAMA_MODEL = os.environ.get("OLLAMA_MODEL", "").strip()
# Ollama 컨텍스트 윈도우 크기. 명시하지 않으면 Ollama가 모델 기본값(수천 토큰)을 사용해
# 대화가 길어지면 400 에러가 발생할 수 있다. 0이면 주입하지 않음.
OLLAMA_NUM_CTX = int(os.environ.get("OLLAMA_NUM_CTX", 16384))
# Ollama 프록시 API 키 — 외부에서 /ai/v1/* 에 접근할 때 필요한 인증 키
# 환경변수로 주입하거나 여기서 직접 설정
OLLAMA_PROXY_API_KEY = load_optional_secret("OLLAMA_PROXY_API_KEY", "")  # 비어있으면 인증 없음

# Cloudflare Turnstile 설정 - 디버그 모드에서는 비활성화
if DEBUG:
    TURNSTILE_SITE_KEY = ""
    TURNSTILE_SECRET_KEY = ""
else:
    TURNSTILE_SITE_KEY = load_optional_secret("TURNSTILE_SITE_KEY", "")
TURNSTILE_SECRET_KEY = load_optional_secret("TURNSTILE_SECRET_KEY", "")

# Daily local backup settings (loaded from config/secrets.json or env)
DATA_BACKUP_ROOT = load_optional_secret("DATA_BACKUP_ROOT", "")
DATA_BACKUP_RETENTION_DAYS = max(1, load_optional_int_secret("DATA_BACKUP_RETENTION_DAYS", 3))

ALLOWED_HOSTS = env_list(
    "DJANGO_ALLOWED_HOSTS",
    "hanplanet.com,www.hanplanet.com,mc.hanplanet.com,localhost,127.0.0.1,52.79.71.20,112.187.212.49,112.187.212.140",
)

PUBLIC_BASE_URL = os.environ.get("PUBLIC_BASE_URL", "https://www.hanplanet.com").rstrip("/")
WARGAME_PUBLIC_URL = os.environ.get(
    "WARGAME_PUBLIC_URL",
    "https://wargame.hanplanet.com/",
).rstrip("/")
CANONICAL_PUBLIC_HOST_REDIRECT = load_optional_bool_secret(
    "CANONICAL_PUBLIC_HOST_REDIRECT",
    default=not DEBUG and not RUNNING_TESTS,
)
DJANGO_SERVE_FILES = env_bool("DJANGO_SERVE_FILES", default=True)
GAME_WS_PUBLIC_URL = os.environ.get("GAME_WS_PUBLIC_URL", "wss://game.hanplanet.com").rstrip("/")
GAME_WS_LOCAL_URL = os.environ.get("GAME_WS_LOCAL_URL", "ws://127.0.0.1:8081").rstrip("/")
GAME_ADMIN_URL = os.environ.get("GAME_ADMIN_URL", "http://127.0.0.1:8082").rstrip("/")
BUMPERCAR_SPIKY_SETTINGS_PATH = os.environ.get("BUMPERCAR_SPIKY_SETTINGS_PATH", "").strip()
GAME_JWT_SECRET = load_optional_secret("GAME_JWT_SECRET", SECRET_KEY)
GAME_JWT_ISSUER = load_optional_secret("GAME_JWT_ISSUER", PUBLIC_BASE_URL).rstrip("/")
GAME_JWT_AUDIENCE = load_optional_secret("GAME_JWT_AUDIENCE", "hanplanet-game")
GAME_JWT_EXP_SECONDS = max(30, load_optional_int_secret("GAME_JWT_EXP_SECONDS", 300))
WARGAME_COMPLETION_SECRET = load_optional_secret("WARGAME_COMPLETION_SECRET", "")
WARGAME_OIDC_CLIENT_ID = os.environ.get("WARGAME_OIDC_CLIENT_ID", "hanplanet-wargame-sso").strip()
WARGAME_OIDC_CLIENT_SECRET = load_optional_secret("WARGAME_OIDC_CLIENT_SECRET", "")
WARGAME_OIDC_REDIRECT_URI = os.environ.get(
    "WARGAME_OIDC_REDIRECT_URI",
    f"{WARGAME_PUBLIC_URL}/auth/callback.php",
).strip()
FORGEJO_OIDC_SSO_ENABLED = env_bool(
    "FORGEJO_OIDC_SSO_ENABLED",
    default=not DEBUG and not RUNNING_TESTS,
)
FORGEJO_OIDC_CLIENT_ID = os.environ.get("FORGEJO_OIDC_CLIENT_ID", "gitea-hanplanet-sso").strip()
MINECRAFT_LINK_SHARED_SECRET = load_optional_secret("MINECRAFT_LINK_SHARED_SECRET", "")
MINECRAFT_LINK_CODE_TTL_SECONDS = max(60, load_optional_int_secret("MINECRAFT_LINK_CODE_TTL_SECONDS", 600))
MINECRAFT_LINK_HMAC_SKEW_SECONDS = max(30, load_optional_int_secret("MINECRAFT_LINK_HMAC_SKEW_SECONDS", 300))
HANPLANET_RUNTIME = os.environ.get("HANPLANET_RUNTIME", "").strip().lower()
MINECRAFT_SERVER_DIR = os.environ.get("MINECRAFT_SERVER_DIR", "/Users/imhanbyeol/Development/minecraft").strip()
MINECRAFT_CONSOLE_TRANSPORT = os.environ.get(
    "MINECRAFT_CONSOLE_TRANSPORT",
    "rcon" if HANPLANET_RUNTIME == "docker" else "fifo",
).strip().lower()
MINECRAFT_RCON_HOST = load_optional_secret(
    "MINECRAFT_RCON_HOST",
    "host.docker.internal" if HANPLANET_RUNTIME == "docker" else "127.0.0.1",
)
MINECRAFT_RCON_PORT = load_optional_int_secret("MINECRAFT_RCON_PORT", 25575)
MINECRAFT_RCON_PASSWORD = load_optional_secret("MINECRAFT_RCON_PASSWORD", "")
MINECRAFT_RCON_TIMEOUT_SECONDS = max(1, load_optional_int_secret("MINECRAFT_RCON_TIMEOUT_SECONDS", 3))
MAP_COLLAB_WS_PUBLIC_URL  = os.environ.get("MAP_COLLAB_WS_PUBLIC_URL",  "wss://map-collab.hanplanet.com").rstrip("/")
MAP_COLLAB_WS_LOCAL_URL   = os.environ.get("MAP_COLLAB_WS_LOCAL_URL",   "ws://127.0.0.1:8083").rstrip("/")
MAP_COLLAB_ADMIN_URL      = os.environ.get("MAP_COLLAB_ADMIN_URL",      "http://127.0.0.1:8084").rstrip("/")

# Celery 설정 (Redis 브로커, Django DB 결과 백엔드)
CELERY_BROKER_URL                         = os.environ.get("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND                     = "django-db"
CELERY_CACHE_BACKEND                      = "default"
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TASK_ACKS_LATE                     = True
CELERY_WORKER_PREFETCH_MULTIPLIER         = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD         = 50
CELERY_BROKER_TRANSPORT_OPTIONS           = {"visibility_timeout": 3600}
HANDRIVE_TUTORIAL_WORKSPACE_MAX_AGE_SECONDS = max(
    60,
    load_optional_int_secret("HANDRIVE_TUTORIAL_WORKSPACE_MAX_AGE_SECONDS", 60 * 60 * 24),
)
HANDRIVE_TUTORIAL_WORKSPACE_CLEANUP_INTERVAL_SECONDS = max(
    60,
    load_optional_int_secret("HANDRIVE_TUTORIAL_WORKSPACE_CLEANUP_INTERVAL_SECONDS", 60 * 60),
)
CELERY_BEAT_SCHEDULE = {
    # 만료된 Django 세션 매일 새벽 3시 정리
    "clearsessions-daily": {
        "task": "main.tasks.clear_expired_sessions",
        "schedule": 60 * 60 * 24,  # 24시간마다
    },
    # 완료/스킵 없이 이탈한 HanDrive 튜토리얼 임시 드라이브 정리
    "handrive-tutorial-workspace-cleanup": {
        "task": "main.tasks.cleanup_stale_handrive_tutorial_workspaces",
        "schedule": HANDRIVE_TUTORIAL_WORKSPACE_CLEANUP_INTERVAL_SECONDS,
    },
}

# Forgejo 설정
DISC = get_disc_mode()
FORGEJO_BASE_URL    = load_optional_secret("FORGEJO_BASE_URL", "http://localhost:3000")
FORGEJO_ADMIN_TOKEN = load_optional_secret("FORGEJO_ADMIN_TOKEN", "")
PUBLIC_GIT_BASE_URL = load_optional_secret("PUBLIC_GIT_BASE_URL", "http://localhost:3000")
FORGEJO_REPOS_ROOT  = str(get_forgejo_repos_root(DISC))

# GitHub App 설정
GITHUB_APP_CLIENT_ID     = load_optional_secret("GITHUB_APP_CLIENT_ID", "")
GITHUB_APP_CLIENT_SECRET = load_optional_secret("GITHUB_APP_CLIENT_SECRET", "")
GITHUB_AUTH_CALLBACK_URL = load_optional_secret("GITHUB_AUTH_CALLBACK_URL", "")
GITHUB_AUTH_SCOPE        = load_optional_secret("GITHUB_AUTH_SCOPE", "repo user:email")
GITHUB_AUTH_AUTHORIZE_URL = load_optional_secret("GITHUB_AUTH_AUTHORIZE_URL", "https://github.com/login/oauth/authorize")
GITHUB_AUTH_TOKEN_URL     = load_optional_secret("GITHUB_AUTH_TOKEN_URL", "https://github.com/login/oauth/access_token")
GITHUB_API_BASE_URL       = load_optional_secret("GITHUB_API_BASE_URL", "https://api.github.com")
GITHUB_API_VERSION        = load_optional_secret("GITHUB_API_VERSION", "2022-11-28")
GITHUB_REPO_CACHE_ROOT    = str(get_github_repo_cache_root(DISC))

# Bungie API settings for Destiny utility pages
BUNGIE_API_KEY      = load_optional_secret("BUNGIE_API_KEY", "")
BUNGIE_API_BASE_URL = load_optional_secret("BUNGIE_API_BASE_URL", "https://www.bungie.net/Platform")
BUNGIE_MEDIA_BASE_URL = load_optional_secret("BUNGIE_MEDIA_BASE_URL", "https://www.bungie.net")

# Google OAuth 설정
GOOGLE_AUTH_CLIENT_ID     = load_optional_secret("GOOGLE_AUTH_CLIENT_ID", "")
GOOGLE_AUTH_CLIENT_SECRET = load_optional_secret("GOOGLE_AUTH_CLIENT_SECRET", "")
GOOGLE_AUTH_CALLBACK_URL  = load_optional_secret("GOOGLE_AUTH_CALLBACK_URL", "")
GOOGLE_AUTH_BASE_SCOPE    = load_optional_secret("GOOGLE_AUTH_BASE_SCOPE", "openid email profile")
GOOGLE_AUTH_DRIVE_FILE_SCOPE = load_optional_secret("GOOGLE_AUTH_DRIVE_FILE_SCOPE", "https://www.googleapis.com/auth/drive.file")
GOOGLE_AUTH_SCOPE         = load_optional_secret("GOOGLE_AUTH_SCOPE", GOOGLE_AUTH_BASE_SCOPE)
GOOGLE_AUTH_AUTHORIZE_URL = load_optional_secret("GOOGLE_AUTH_AUTHORIZE_URL", "https://accounts.google.com/o/oauth2/v2/auth")
GOOGLE_AUTH_TOKEN_URL     = load_optional_secret("GOOGLE_AUTH_TOKEN_URL", "https://oauth2.googleapis.com/token")
GOOGLE_AUTH_USERINFO_URL  = load_optional_secret("GOOGLE_AUTH_USERINFO_URL", "https://www.googleapis.com/oauth2/v3/userinfo")
GOOGLE_PICKER_API_KEY     = load_optional_secret("GOOGLE_PICKER_API_KEY", "")
GOOGLE_PICKER_APP_ID      = load_optional_secret("GOOGLE_PICKER_APP_ID", GOOGLE_AUTH_CLIENT_ID.split("-", 1)[0] if GOOGLE_AUTH_CLIENT_ID else "")

# MinIO (S3 호환 오브젝트 스토리지) 설정
MINIO_ENDPOINT        = load_optional_secret("MINIO_ENDPOINT", "localhost:9000")
MINIO_ACCESS_KEY      = load_optional_secret("MINIO_ACCESS_KEY", "minioadmin")
MINIO_SECRET_KEY      = load_optional_secret("MINIO_SECRET_KEY", "minioadmin")
MINIO_BUCKET          = load_optional_secret("MINIO_BUCKET", "handrive")
MINIO_SECURE          = load_optional_bool_secret("MINIO_SECURE", default=False)
MINIO_PUBLIC_ENDPOINT = load_optional_secret("MINIO_PUBLIC_ENDPOINT", MINIO_ENDPOINT)
MINIO_PUBLIC_SECURE   = load_optional_bool_secret("MINIO_PUBLIC_SECURE", default=MINIO_SECURE)

# Sync Client JWT 설정
SYNC_JWT_SECRET              = load_optional_secret("SYNC_JWT_SECRET", SECRET_KEY)
SYNC_JWT_ACCESS_EXP_SECONDS  = max(300, load_optional_int_secret("SYNC_JWT_ACCESS_EXP_SECONDS", 3600))
SYNC_JWT_REFRESH_EXP_SECONDS = max(3600, load_optional_int_secret("SYNC_JWT_REFRESH_EXP_SECONDS", 86400 * 30))

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'portfolio',
    'stratagem',
    'git',
    'ai',
    'hpmail',
    'corsheaders',
    'django_celery_results',
    'oauth2_provider',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "main.middleware.CanonicalPublicHostMiddleware",
    "django.middleware.gzip.GZipMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "main.middleware.UiLanguagePreferenceCookieMiddleware",
    "django.middleware.common.CommonMiddleware",
    "main.middleware.GlobalRateLimitMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "main.middleware.HanplanetAccountActiveCookieMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "main.context_processors.site_meta_defaults",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": Path(os.environ.get("DJANGO_SQLITE_PATH", BASE_DIR / "db.sqlite3")),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True

GLOBAL_RATE_LIMIT_CACHE_ALIAS = os.environ.get("DJANGO_GLOBAL_RATE_LIMIT_CACHE_ALIAS", "rate_limit")
GLOBAL_RATE_LIMIT_CACHE_DIR = os.environ.get(
    "DJANGO_GLOBAL_RATE_LIMIT_CACHE_DIR",
    "/tmp/hanplanet_rate_limit_cache",
)

# Cache settings
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 60 * 60 * 24,  # 24시간 캐시 유지
    },
    'rate_limit': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': GLOBAL_RATE_LIMIT_CACHE_DIR,
        'TIMEOUT': 60 * 60 * 24,
    },
}

GLOBAL_RATE_LIMIT_ENABLED = env_bool("DJANGO_GLOBAL_RATE_LIMIT_ENABLED", default=True)
GLOBAL_RATE_LIMIT_REQUESTS = max(
    1, int(os.environ.get("DJANGO_GLOBAL_RATE_LIMIT_REQUESTS", "240"))
)
GLOBAL_RATE_LIMIT_WINDOW_SECONDS = max(
    1, int(os.environ.get("DJANGO_GLOBAL_RATE_LIMIT_WINDOW_SECONDS", "60"))
)
GLOBAL_RATE_LIMIT_EXEMPT_PATH_PREFIXES = tuple(
    env_list(
        "DJANGO_GLOBAL_RATE_LIMIT_EXEMPT_PATH_PREFIXES",
        "/static/,/media/,/ko/sub/onscripter/assets/,/en/sub/onscripter/assets/",
    )
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

MEDIA_URL = "/media/"
MEDIA_ROOT = str(get_media_root(DISC))
_default_onscripter_root = (
    Path(MEDIA_ROOT).parent / "ONScripter"
    if Path(MEDIA_ROOT).name == "media"
    else Path(MEDIA_ROOT) / "ONScripter"
)
ONSCRIPTER_STORAGE_ROOT = load_optional_secret(
    "HANPLANET_ONSCRIPTER_ROOT",
    str(_default_onscripter_root),
)
HANPLANET_CLI_ROOT = load_optional_secret(
    "HANPLANET_CLI_ROOT",
    str(Path(MEDIA_ROOT).parent / "HanPlanet-CLI"),
)
HANDRIVE_HLS_CACHE_ROOT = load_optional_secret(
    "HANDRIVE_HLS_CACHE_ROOT",
    str(get_media_root("hdd") / "hls_cache"),
)

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

# 로깅 설정
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'timestamped': {
            'format': '%(asctime)s %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'debug.log'),
            'formatter': 'timestamped',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'main': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'ai': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#     }
# }
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# 디버그 모드에서는 HTTPS 리다이렉트 비활성화
SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", default=False) if not DEBUG else False
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", default=DEFAULT_SECURE_TRANSPORT) if not DEBUG else False
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SHARED_COOKIE_DOMAIN = env_cookie_domain(
    "DJANGO_COOKIE_DOMAIN",
    ".hanplanet.com" if DEFAULT_SECURE_TRANSPORT else None,
)
SESSION_COOKIE_DOMAIN = SHARED_COOKIE_DOMAIN
SESSION_SAVE_EVERY_REQUEST = env_bool(
    "DJANGO_SESSION_SAVE_EVERY_REQUEST",
    default=bool(SESSION_COOKIE_DOMAIN),
)
SESSION_COOKIE_AGE = 60 * 60 * 24  # 1일
SESSION_ENGINE = "django.contrib.sessions.backends.db"  # LocMemCache 세션 방지
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", default=DEFAULT_SECURE_TRANSPORT) if not DEBUG else False
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_DOMAIN = None
SECURE_HSTS_SECONDS = int(
    os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "31536000" if DEFAULT_SECURE_TRANSPORT else "0")
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
    default=(DEFAULT_SECURE_TRANSPORT and SECURE_HSTS_SECONDS > 0),
)
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", default=False)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = os.environ.get("DJANGO_SECURE_REFERRER_POLICY", "strict-origin-when-cross-origin")
X_FRAME_OPTIONS = "DENY"
CSRF_FAILURE_VIEW = "main.handrive_views.handrive_csrf_failure"

# 로컬/컨테이너 게임 서버 → Django 내부 API 인증 시크릿 (설정 시 요청에 X-Internal-Secret 헤더 필요)
BUMPERCAR_SPIKY_INTERNAL_SECRET = load_optional_secret("BUMPERCAR_SPIKY_INTERNAL_SECRET", "")

# config/settings.py

# 1) HTTPS에서 CSRF 신뢰 도메인 지정 (Django 4+는 스킴 포함해야 함)
CSRF_TRUSTED_ORIGINS = env_list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    "https://hanplanet.com,https://www.hanplanet.com,https://mc.hanplanet.com",
)
CSRF_TRUSTED_ORIGINS = [
    origin for origin in CSRF_TRUSTED_ORIGINS
    if origin.rstrip("/") != "https://wargame.hanplanet.com"
]
if "https://mc.hanplanet.com" not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append("https://mc.hanplanet.com")

# ── OAuth2 Provider (Gitea SSO) ──────────────────────────────
OAUTH2_PROVIDER = {
    'SCOPES': {
        'openid': 'OpenID Connect',
        'profile': '프로필 정보',
        'email': '이메일 주소',
    },
    'ACCESS_TOKEN_EXPIRE_SECONDS': 3600,
    'REFRESH_TOKEN_EXPIRE_SECONDS': 86400 * 30,
    'ROTATE_REFRESH_TOKEN': True,
    'OIDC_ENABLED': True,
    'OIDC_RSA_PRIVATE_KEY': load_optional_secret('OIDC_RSA_PRIVATE_KEY', ''),
    'PKCE_REQUIRED': False,  # Forgejo OAuth2 클라이언트(confidential)가 PKCE 미지원
    'OAUTH2_VALIDATOR_CLASS': 'main.oauth2_validators.HanplanetOAuth2Validator',
}
AUTHENTICATION_BACKENDS = [
    'oauth2_provider.backends.OAuth2Backend',
    'django.contrib.auth.backends.ModelBackend',
]

# OAuth2 인증 시 리디렉션할 로그인 URL
LOGIN_URL = '/ko/login'

# ── Email 2FA ─────────────────────────────────────────────────────────────────
EMAIL_BACKEND = (
    "django.core.mail.backends.console.EmailBackend" if DEBUG
    else "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = load_optional_secret("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = load_optional_int_secret("EMAIL_PORT", 587)
EMAIL_USE_TLS = load_optional_bool_secret("EMAIL_USE_TLS", True)
EMAIL_HOST_USER = load_optional_secret("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = load_optional_secret("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = load_optional_secret("DEFAULT_FROM_EMAIL", "noreply@hanplanet.com")
TWO_FA_CODE_EXPIRY_MINUTES = 10
TWO_FA_DEVICE_COOKIE_NAME = "hp_device_id"
TWO_FA_DEVICE_TRUSTED_DAYS = 3
TWO_FA_DEVICE_COOKIE_AGE = 60 * 60 * 24 * 3  # 3일

# ── HPmail ────────────────────────────────────────────────────────────────────
HPMAIL_DOMAIN = load_optional_secret("HPMAIL_DOMAIN", "hanplanet.com")
HPMAIL_DEFAULT_ATTACHMENT_LIMIT_BYTES = load_optional_int_secret("HPMAIL_DEFAULT_ATTACHMENT_LIMIT_BYTES", 25 * 1024 * 1024)
HPMAIL_DEFAULT_DAILY_SEND_LIMIT = load_optional_int_secret("HPMAIL_DEFAULT_DAILY_SEND_LIMIT", 100)
HPMAIL_STORAGE_ROOT = load_optional_secret(
    "HPMAIL_STORAGE_ROOT",
    str(get_media_root(DISC).parent / "mail"),
)
HPMAIL_IMAP_HOST = load_optional_secret("HPMAIL_IMAP_HOST", "127.0.0.1")
HPMAIL_IMAP_PORT = load_optional_int_secret("HPMAIL_IMAP_PORT", 143)
HPMAIL_IMAP_USE_TLS = load_optional_bool_secret("HPMAIL_IMAP_USE_TLS", False)
HPMAIL_IMAP_TIMEOUT = load_optional_int_secret("HPMAIL_IMAP_TIMEOUT", 10)
HPMAIL_IMAP_MASTER_USER = load_optional_secret("HPMAIL_IMAP_MASTER_USER", "")
HPMAIL_IMAP_MASTER_PASSWORD = load_optional_secret("HPMAIL_IMAP_MASTER_PASSWORD", "")
HPMAIL_IMAP_MASTER_LOGIN_FORMAT = load_optional_secret(
    "HPMAIL_IMAP_MASTER_LOGIN_FORMAT",
    "{email}*{master_user}",
)
HPMAIL_SMTP_HOST = load_optional_secret("HPMAIL_SMTP_HOST", "127.0.0.1")
HPMAIL_SMTP_PORT = load_optional_int_secret("HPMAIL_SMTP_PORT", 25)
HPMAIL_SMTP_USE_TLS = load_optional_bool_secret("HPMAIL_SMTP_USE_TLS", False)
HPMAIL_SMTP_TIMEOUT = load_optional_int_secret("HPMAIL_SMTP_TIMEOUT", 10)
HPMAIL_SMTP_USERNAME = load_optional_secret("HPMAIL_SMTP_USERNAME", "")
HPMAIL_SMTP_PASSWORD = load_optional_secret("HPMAIL_SMTP_PASSWORD", "")
