# Generated by Django 4.2.24 on 2026-06-11 07:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import hpmail.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_part', models.CharField(max_length=64, verbose_name='메일 주소 ID')),
                ('domain', models.CharField(default=hpmail.models.get_default_domain, max_length=255, verbose_name='도메인')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='사용 가능')),
                ('external_clients_enabled', models.BooleanField(default=False, help_text='웹메일 외부의 메일 클라이언트 접속 허용 여부입니다. 앱 비밀번호와 함께 사용합니다.', verbose_name='외부 IMAP/SMTP 클라이언트 허용')),
                ('attachment_limit_bytes', models.BigIntegerField(blank=True, help_text='비워두면 HPmail 기본 정책을 따릅니다.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='사용자별 첨부파일 제한(bytes)')),
                ('daily_send_limit', models.PositiveIntegerField(blank=True, help_text='비워두면 HPmail 기본 정책을 따릅니다.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='사용자별 일일 발송 제한')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hpmail_account', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'HPmail 계정',
                'verbose_name_plural': 'HPmail 계정',
            },
        ),
        migrations.CreateModel(
            name='MailSitePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('default_attachment_limit_bytes', models.BigIntegerField(default=hpmail.models.get_default_attachment_limit_bytes, help_text='사용자별 override가 없을 때 적용되는 첨부파일 총량 제한입니다.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='기본 첨부파일 제한(bytes)')),
                ('default_daily_send_limit', models.PositiveIntegerField(default=hpmail.models.get_default_daily_send_limit, help_text='사용자별 override가 없을 때 적용되는 하루 발송 건수 제한입니다.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='기본 일일 발송 제한')),
                ('max_recipients_per_message', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)], verbose_name='메일당 최대 수신자 수')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': 'HPmail 기본 정책',
                'verbose_name_plural': 'HPmail 기본 정책',
            },
        ),
        migrations.CreateModel(
            name='MailDailySendCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='발송 건수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_send_counters', to='hpmail.mailaccount', verbose_name='메일 계정')),
            ],
            options={
                'verbose_name': 'HPmail 일일 발송량',
                'verbose_name_plural': 'HPmail 일일 발송량',
            },
        ),
        migrations.CreateModel(
            name='MailAppPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='이름')),
                ('token_prefix', models.CharField(db_index=True, max_length=12, verbose_name='토큰 앞부분')),
                ('token_hash', models.CharField(max_length=255, verbose_name='토큰 해시')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 가능')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 사용일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='폐기일')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_passwords', to='hpmail.mailaccount', verbose_name='메일 계정')),
            ],
            options={
                'verbose_name': 'HPmail 앱 비밀번호',
                'verbose_name_plural': 'HPmail 앱 비밀번호',
            },
        ),
        migrations.CreateModel(
            name='MailAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_part', models.CharField(max_length=64, verbose_name='별칭 주소 ID')),
                ('domain', models.CharField(default=hpmail.models.get_default_domain, max_length=255, verbose_name='도메인')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='사용 가능')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('target_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='hpmail.mailaccount', verbose_name='전달 대상 계정')),
            ],
            options={
                'verbose_name': 'HPmail 별칭',
                'verbose_name_plural': 'HPmail 별칭',
            },
        ),
        migrations.CreateModel(
            name='MailMessageIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox', models.CharField(default='INBOX', max_length=255, verbose_name='메일함')),
                ('uid', models.CharField(max_length=64, verbose_name='IMAP UID')),
                ('message_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Message-ID')),
                ('subject', models.CharField(blank=True, default='', max_length=500, verbose_name='제목')),
                ('sender', models.CharField(blank=True, default='', max_length=500, verbose_name='보낸 사람')),
                ('recipients', models.JSONField(blank=True, default=list, verbose_name='받는 사람')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='발송 시각')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='수신 시각')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='크기(bytes)')),
                ('has_attachments', models.BooleanField(default=False, verbose_name='첨부 있음')),
                ('flags', models.JSONField(blank=True, default=list, verbose_name='IMAP 플래그')),
                ('indexed_at', models.DateTimeField(auto_now=True, verbose_name='색인일')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_indexes', to='hpmail.mailaccount', verbose_name='메일 계정')),
            ],
            options={
                'verbose_name': 'HPmail 메시지 색인',
                'verbose_name_plural': 'HPmail 메시지 색인',
                'indexes': [models.Index(fields=['account', 'mailbox', 'received_at'], name='hpmail_mail_account_1b8464_idx'), models.Index(fields=['message_id'], name='hpmail_mail_message_4ca11e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='mailmessageindex',
            constraint=models.UniqueConstraint(fields=('account', 'mailbox', 'uid'), name='unique_hpmail_message_uid'),
        ),
        migrations.AddIndex(
            model_name='maildailysendcounter',
            index=models.Index(fields=['date'], name='hpmail_mail_date_15545e_idx'),
        ),
        migrations.AddConstraint(
            model_name='maildailysendcounter',
            constraint=models.UniqueConstraint(fields=('account', 'date'), name='unique_hpmail_daily_send_counter'),
        ),
        migrations.AddIndex(
            model_name='mailapppassword',
            index=models.Index(fields=['account', 'is_active'], name='hpmail_mail_account_75bde4_idx'),
        ),
        migrations.AddIndex(
            model_name='mailalias',
            index=models.Index(fields=['local_part', 'domain'], name='hpmail_mail_local_p_e36919_idx'),
        ),
        migrations.AddConstraint(
            model_name='mailalias',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('local_part'), django.db.models.functions.text.Lower('domain'), name='unique_hpmail_alias_address_ci'),
        ),
        migrations.AddIndex(
            model_name='mailaccount',
            index=models.Index(fields=['user'], name='hpmail_mail_user_id_70586c_idx'),
        ),
        migrations.AddIndex(
            model_name='mailaccount',
            index=models.Index(fields=['local_part', 'domain'], name='hpmail_mail_local_p_f56e1f_idx'),
        ),
        migrations.AddConstraint(
            model_name='mailaccount',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('local_part'), django.db.models.functions.text.Lower('domain'), name='unique_hpmail_account_address_ci'),
        ),
    ]
