# Generated by Django 4.2.24 on 2026-04-09 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AITokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='모델')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, verbose_name='입력 토큰')),
                ('completion_tokens', models.PositiveIntegerField(default=0, verbose_name='출력 토큰')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='합계 토큰')),
                ('is_stream', models.BooleanField(default=False, verbose_name='스트리밍')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='요청 시각')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_token_usage', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'AI 토큰 사용 기록',
                'verbose_name_plural': 'AI 토큰 사용 기록',
                'ordering': ['-created_at'],
            },
        ),
    ]
