# Generated by Django 4.2.24 on 2026-04-17 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitokenusage',
            name='is_estimated',
            field=models.BooleanField(default=False, verbose_name='추정치'),
        ),
        migrations.AddField(
            model_name='aitokenusage',
            name='request_user',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150, verbose_name='요청자'),
        ),
        migrations.AlterField(
            model_name='aitokenusage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_token_usage', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
