<?php
declare(strict_types=1);

return [
    [
        'id' => 'web-v1-01-http',
        'module' => '01-http-and-trust',
        'order' => 10,
        'title' => 'HTTP 요청 지도 읽기',
        'eyebrow' => '모듈 1 · 웹의 언어',
        'difficulty' => '입문',
        'minutes' => 20,
        'prerequisites' => [],
        'client' => '오로라 문구점',
        'story' => '오로라 문구점은 내일 오전 9시 여름 기획전을 엽니다. 오늘 새벽 사전 체험 고객 한 명이 공개된 ‘할인 확인’ 화면을 새로고침하던 중 직원용으로 보이는 서비스 상태 화면을 보았다고 신고했습니다. 직원 로그인 기록은 없었고 주문·결제 정보 노출 여부도 아직 확인되지 않았습니다. 온라인영업팀은 행사 오픈 여부를 결정하기 위해 외부 방문자 권한만으로 같은 현상이 재현되는지 긴급 검증을 요청했습니다.',
        'brief' => '공개 방문자 상태로 Aurora SmartCoupon의 할인 확인 화면을 블랙박스 방식으로 점검하세요. 브라우저 개발자 도구나 로컬 프록시로 자신의 요청과 응답을 관찰·재전송할 수 있습니다. 직원용 화면에 인증 없이 도달할 수 있는지 확인하고, 재현 시각과 최소한의 요청·응답 증거를 보존하세요.',
        'target' => [
            'objective' => '일반 고객 권한으로 직원용 서비스 상태 화면에 도달할 수 있음을 재현하고 요청·응답 증거를 확보하세요.',
            'entry_url' => '/aurora/discount/check',
            'service_name' => 'Aurora SmartCoupon',
            'hostname' => 'coupon.aurora-stationery.training',
            'entry_path' => '/discount/check',
            'access_method' => '의뢰 메일에 포함된 승인 링크로 공개 할인 확인 화면 접속',
            'environment' => '여름 기획전 할인 조회 서비스 · 주문과 결제는 별도 시스템에서 처리',
            'surface' => '고객 할인 조회 · HTTP 요청과 응답 · 직원용 상태 화면 권한 경계',
        ],
        'email' => [
            'subject' => '[긴급 외부 검증] 할인 확인 화면에서 직원용 상태 화면 노출 신고',
            'sender' => ['name' => '한서윤', 'role' => '온라인영업 운영팀 대리', 'organization' => '오로라 문구점 주식회사', 'address' => 'seoyun.han@aurora-stationery.training'],
            'urgency' => '높음 · 내일 09:00 기획전 오픈 전 1차 판단 필요',
            'contact_context' => '지난달 결제 페이지 점검을 도와준 FIELD//OPS 담당자의 소개로 연락드립니다. 법무·인프라 팀이 아래 공개 자산에 대한 제한적 블랙박스 검증을 승인했으며, 승인 시간 동안의 요청은 당사 관제팀이 모니터링합니다.',
            'scope' => [
                'coupon.aurora-stationery.training의 할인 확인 화면과 같은 host에서 직접 연결되는 읽기 전용 화면만 조사',
                '자신의 브라우저 요청 관찰, 수동 재전송, 요청 구성 변경 허용',
                '주문·고객·결제 기능, 계정 생성, 다른 host 탐색은 범위 외',
            ],
            'deliverables' => [
                '재현 시각, 시작 URL, 일반 고객임을 확인할 수 있는 세션 상태',
                '직원용 화면에 도달한 최종 요청·응답과 화면 증거',
                '고객 화면과 운영 기능의 권한 경계를 분리하기 위한 단기·근본 조치',
            ],
            'cautions' => ['할인 조회는 반복해도 되지만 주문 생성이나 고객 정보 조회는 시도하지 말아 주세요.', '메일에 명시된 자산 밖의 주소로는 요청하지 말아 주세요.'],
            'closing' => '행사 오픈 여부를 결정해야 하므로, 직원용 화면이 재현되면 더 넓게 탐색하지 말고 확보한 증거와 함께 즉시 결과를 제출해 주세요.',
            'cta_label' => '오로라 할인 확인 화면에 접속',
        ],
        'objectives' => [
            'HTTP 요청의 method, path, query, header, body를 구분한다.',
            '응답의 status, header, body가 서로 다른 정보를 전달한다는 점을 확인한다.',
            '화면에 보이지 않는 네트워크 정보를 개발자 도구에서 찾는다.',
        ],
        'lesson' => [
            'summary' => '학습 노트 · 웹 해킹의 첫 단계는 화면을 보는 것이 아니라 브라우저와 서버가 주고받는 메시지를 읽는 것입니다.',
            'paragraphs' => [
                '브라우저는 주소와 폼 입력을 HTTP 요청으로 바꾸고, 서버는 상태 코드·헤더·본문으로 이루어진 응답을 돌려줍니다. 같은 화면을 열어도 method나 header가 달라지면 서버가 전혀 다른 동작을 할 수 있습니다.',
                '개발자 도구의 Network 패널에서는 요청 URL, method, 요청 헤더, 폼 데이터, 응답 헤더와 본문을 각각 볼 수 있습니다. Elements 패널은 최종 화면을 보여 주지만 Network 패널은 그 화면이 만들어진 과정을 보여 줍니다.',
                '승인된 블랙박스 점검에서는 의뢰서에 적힌 host와 화면에서 직접 확인한 같은 출처의 읽기 전용 경로만 요청해야 합니다. 개발자 도구와 프록시는 승인 범위를 넓혀 주는 도구가 아닙니다.',
            ],
            'diagram' => '/assets/lessons/http-flow.svg',
            'table' => [
                'columns' => ['구성 요소', '예시', '확인할 질문'],
                'rows' => [
                    ['Method', 'GET, POST', '읽기 요청인가, 상태를 바꾸는 요청인가?'],
                    ['Path / Query', '/coupon?code=SPRING', '어떤 자원과 입력값을 선택하는가?'],
                    ['Request Header', 'Accept-Language: ko-KR', '브라우저가 서버에 어떤 문맥을 전달하는가?'],
                    ['Response Header', 'Link: </help>; rel=help', '본문 밖에서 서버가 어떤 관계 정보를 주는가?'],
                    ['Response Body', 'HTML 또는 JSON', '서버가 처리 결과를 어떻게 표현하는가?'],
                ],
            ],
            'code' => [
                'language' => 'http',
                'content' => "GET /aurora/discount/check HTTP/1.1\nHost: coupon.aurora-stationery.training\nAccept: text/html\n\nHTTP/1.1 200 OK\nContent-Type: text/html; charset=utf-8\nCache-Control: no-store",
            ],
        ],
        'resources' => [
            ['label' => 'MDN · HTTP 개요', 'url' => 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Overview'],
            ['label' => 'MDN · HTTP 메시지', 'url' => 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Messages'],
        ],
        'hints' => [
            ['level' => 1, 'title' => '요청을 다시 관찰하기', 'body' => '개발자 도구를 연 뒤 페이지를 새로고침하고 Network 목록에서 document 요청을 선택하세요.'],
            ['level' => 2, 'title' => '본문 밖의 정보', 'body' => 'Headers 탭의 Response Headers를 살펴보고 일반 고객 응답에 어울리지 않는 운영 관련 값이나 URL 형태의 단서를 찾으세요.'],
            ['level' => 3, 'title' => '요청 문맥 비교', 'body' => '응답이 가리킨 같은 host의 위치를 요청한 뒤 정상 고객 요청과 무엇이 다른지 비교하세요. 브라우저가 자동으로 보내지 않는 값은 로컬 프록시의 재전송 기능으로 확인할 수 있습니다.'],
        ],
        'lab' => ['type' => 'http_headers'],
        'completion' => [
            'event' => 'http_diagnostic_reached',
            'email' => [
                'subject' => '[Aurora] 첫 번째 진단 경로 확인 완료',
                'preview' => '요청과 응답을 분리해서 읽었습니다. 다음 미션에서는 브라우저가 보관하는 값을 직접 검증합니다.',
            ],
        ],
    ],
    [
        'id' => 'web-v1-02-client-trust',
        'module' => '01-http-and-trust',
        'order' => 20,
        'title' => '브라우저 값은 권한이 아니다',
        'eyebrow' => '모듈 1 · 신뢰 경계',
        'difficulty' => '입문',
        'minutes' => 25,
        'prerequisites' => ['web-v1-01-http'],
        'client' => '리프 리뷰 센터',
        'story' => '리프 리뷰 센터는 독립 출판사의 원고 검수를 대행합니다. 어제 신규 계약직이 일반 열람자 계정으로 로그인한 직후 검토 책임자 전용 보관함을 보았다는 신고가 접수됐습니다. 계정 관리 기록에는 역할 승격이나 관리자 작업이 없었고, 해당 보관함에는 출간 전 원고가 포함됩니다. 품질·정보보호팀은 다음 출판사 온보딩 전에 접근 통제 실패 여부를 확인해야 합니다.',
        'brief' => '제공된 일반 열람자 계정으로 LeafPeer Review를 블랙박스 방식으로 점검하세요. 브라우저 개발자 도구나 로컬 프록시를 사용해 자신의 세션이 서버로 전달되는 방식을 관찰하고, 계정 역할을 정식으로 변경하지 않은 상태에서 검토 책임자 전용 보관함에 접근할 수 있는지 확인하세요.',
        'target' => [
            'objective' => '일반 열람자 계정으로 검토 책임자 전용 보관함에 접근할 수 있음을 재현하고 역할 불일치 증거를 확보하세요.',
            'entry_url' => '/leaf/inbox',
            'service_name' => 'LeafPeer Review',
            'hostname' => 'review.leaf-center.training',
            'entry_path' => '/inbox',
            'access_method' => '의뢰용 일반 열람자 계정으로 수신함 접속',
            'environment' => '독립 출판사 원고 검토 서비스 · 의뢰 계정에는 공개 샘플 원고만 배정',
            'surface' => '로그인 세션 · 계정 역할 · 검토자 보관함 접근 통제',
        ],
        'email' => [
            'subject' => '[접근 통제 검증] 일반 열람자에게 검토 책임자 보관함이 열린 신고',
            'sender' => ['name' => '문예린', 'role' => '품질·정보보호 책임자', 'organization' => '리프 리뷰 센터', 'address' => 'yerin.moon@leaf-center.training'],
            'urgency' => '보통 이상 · 금주 금요일 신규 출판사 온보딩 전 재현 필요',
            'contact_context' => '개발팀은 화면 표시 오류일 가능성을 제기했지만 감사팀은 서버 측 권한 검사 실패를 배제하지 못했습니다. 조사 계정에는 공개 가능한 샘플 원고만 배정했으며, 아래 자산과 계정에 대한 제한적 검증을 승인합니다.',
            'scope' => ['제공된 일반 열람자 계정과 review.leaf-center.training의 수신함·보관함만 대상', '자신의 세션 요청 관찰과 수동 재전송·변경 허용', '원고 수정·삭제·평점 등록, 다른 계정 접근, 자동화 탐색은 범위 외'],
            'deliverables' => ['검증 시작 시점의 로그인 사용자와 서버가 표시한 계정 역할', '제한 보관함 접근을 재현한 요청·응답 및 화면 증거', '클라이언트가 보낸 값과 무관하게 서버가 역할과 자원 권한을 확인하도록 하는 조치'],
            'cautions' => ['메일에 지정된 계정 밖의 사용자로 로그인하지 마세요.', '제한 보관함이 열리면 추가 원고를 탐색하지 말고 첫 화면만 증거로 남겨 주세요.'],
            'closing' => '감사 보고서에는 일반 열람자가 제한 화면에 도달한 사실, 재현 조건, 영향받는 권한 경계를 명확히 정리해 주세요.',
            'cta_label' => 'LeafPeer 일반 열람자 수신함에 접속',
        ],
        'objectives' => [
            '쿠키가 서버가 아닌 브라우저에 저장되는 값임을 설명한다.',
            'Base64URL 인코딩과 무결성 검증의 차이를 구분한다.',
            '화면 숨김과 서버 측 인가 검사가 다른 통제임을 이해한다.',
        ],
        'lesson' => [
            'summary' => '학습 노트 · 클라이언트가 보관하거나 전송하는 값은 사용자가 바꿀 수 있으므로, 권한의 근거로 단독 사용하면 안 됩니다.',
            'paragraphs' => [
                '쿠키는 서버가 Set-Cookie 응답 헤더로 제안하고 브라우저가 저장한 뒤, 이후 요청의 Cookie 헤더로 다시 보내는 작은 데이터입니다. 개발자 도구나 프록시를 사용하면 사용자는 자신의 브라우저에 저장된 값을 바꿀 수 있습니다.',
                'Base64URL은 데이터를 읽기 쉬운 문자 집합으로 바꾸는 인코딩일 뿐 암호화나 서명이 아닙니다. 디코딩한 JSON의 role 값을 바꾸고 다시 인코딩할 수 있다면 서버는 원본 여부를 판별할 수 없습니다.',
                '안전한 서비스는 서버 세션에서 권한을 조회하거나, 서명된 값을 검증한 뒤에도 현재 권한을 서버 데이터와 대조합니다. 버튼을 숨기는 JavaScript는 편의 기능이지 접근 통제가 아닙니다.',
            ],
            'diagram' => '/assets/lessons/access-control.svg',
            'table' => [
                'columns' => ['통제 위치', '사용자 변경 가능', '보안 판단에 사용'],
                'rows' => [
                    ['숨겨진 버튼 / disabled 속성', '가능', '불가'],
                    ['hidden input', '가능', '불가'],
                    ['서명 없는 role 쿠키', '가능', '불가'],
                    ['서버 세션의 role + 자원별 인가', '직접 변경 불가', '가능'],
                ],
            ],
            'code' => [
                'language' => 'text',
                'content' => "Cookie: leaf_role=eyJyb2xlIjoicmVhZGVyIn0\n\nBase64URL decode\n{\"role\":\"reader\"}\n\n변조 목표\n{\"role\":\"reviewer\"}",
            ],
        ],
        'resources' => [
            ['label' => 'MDN · HTTP 쿠키 사용하기', 'url' => 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Cookies'],
            ['label' => 'OWASP · Authorization Cheat Sheet', 'url' => 'https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html'],
        ],
        'hints' => [
            ['level' => 1, 'title' => '브라우저 저장소 확인', 'body' => 'Application 또는 Storage 패널에서 이 미션 경로에 설정된 leaf_role 쿠키를 찾으세요.'],
            ['level' => 2, 'title' => '인코딩된 JSON', 'body' => '쿠키 값은 Base64URL로 인코딩된 JSON입니다. 패딩이 없어도 디코딩할 수 있습니다.'],
            ['level' => 3, 'title' => '서버가 기대하는 역할', 'body' => 'role 값을 reviewer로 바꾸고 Base64URL로 다시 인코딩한 뒤 페이지를 새로고침하세요.'],
        ],
        'lab' => ['type' => 'role_token'],
        'completion' => [
            'event' => 'review_archive_opened',
            'email' => [
                'subject' => '[Leaf] 리뷰 보관함 접근 기록',
                'preview' => '클라이언트 값만 신뢰하면 화면을 숨겨도 권한을 지킬 수 없습니다.',
            ],
        ],
    ],
    [
        'id' => 'web-v1-03-idor',
        'module' => '01-http-and-trust',
        'order' => 30,
        'title' => '내 문서 번호를 바꾸면?',
        'eyebrow' => '모듈 1 · 접근 통제',
        'difficulty' => '초급',
        'minutes' => 30,
        'prerequisites' => ['web-v1-02-client-trust'],
        'client' => '노바 문서함',
        'story' => '노바 문서함은 소규모 스타트업에 계약서 보관 기능을 제공합니다. 한 고객사가 공유를 해제한 법무 초안이 외부 계약직 계정의 열람 기록에 남았다고 신고했습니다. 서버에는 정상 로그인과 일반적인 문서 조회로만 기록되어 계정 탈취 여부를 판단하기 어렵고, 해당 고객사는 오늘 안으로 노출 범위와 대응 계획을 요구하고 있습니다.',
        'brief' => '제공된 계약직 계정으로 Nova Vault를 블랙박스 방식으로 점검하세요. 자신의 문서함과 화면에 정상적으로 노출되는 활동 정보를 출발점으로 삼아, 명시적으로 공유받지 않은 다른 조직의 지정 문서가 열리는지 확인하세요. 성공하면 로그인 사용자·문서 소유자·최종 응답이 함께 보이는 증거를 남기세요.',
        'target' => [
            'objective' => '계약직 계정으로 공유받지 않은 다른 조직의 지정 문서를 열 수 있음을 재현하고 사용자·소유자 불일치 증거를 확보하세요.',
            'entry_url' => '/nova/documents',
            'service_name' => 'Nova Vault',
            'hostname' => 'docs.nova-office.training',
            'entry_path' => '/documents',
            'access_method' => '의뢰용 외부 계약직 계정으로 문서함 접속',
            'environment' => '기업 계약서 보관 서비스 · 조사 계정에는 공개 가능한 샘플 문서만 소유 문서로 배정',
            'surface' => '문서함 · 최근 활동 · 문서별 소유권과 공유 권한',
        ],
        'email' => [
            'subject' => '[고객 신고 재현] Nova Vault 공유 해제 문서 접근 가능성',
            'sender' => ['name' => '조민재', 'role' => '서비스 신뢰성 매니저', 'organization' => '노바 오피스 클라우드', 'address' => 'minjae.cho@nova-office.training'],
            'urgency' => '높음 · 24시간 내 고객 1차 회신 예정',
            'contact_context' => '고객이 제공한 시각과 당사 접속 기록은 일치하지만, 현재 증거만으로는 화면 오작동과 서버 권한 검사 실패를 구분할 수 없습니다. 아래 계약직 계정과 지정 자산에 대한 읽기 전용 재현을 승인합니다.',
            'scope' => ['제공된 계약직 계정과 docs.nova-office.training의 문서함·최근 활동·문서 열람만 대상', '화면에 노출된 참조값을 이용한 수동 읽기 요청 허용', '문서 편집·삭제·공유, 계정 탐색, 참조값 자동 순회는 범위 외'],
            'deliverables' => ['검증 계정의 사용자와 정상 소유 문서를 보여 주는 시작 상태', '공유되지 않은 지정 문서가 반환된 요청·응답과 소유자 불일치 화면', '모든 문서 요청에서 소유권 또는 명시적 공유 관계를 강제하는 조치'],
            'cautions' => ['화면에 노출되지 않은 문서를 추측하거나 자동으로 열거하지 마세요.', '지정 문서가 열리면 본문 전체를 복사하지 말고 소유자와 증거 표식만 기록하세요.'],
            'closing' => '고객 회신에는 계정 탈취 없이 다른 조직 문서가 열렸는지, 재현 범위와 즉시 차단할 권한 경계를 명확히 적어 주세요.',
            'cta_label' => 'Nova Vault 계약직 문서함에 접속',
        ],
        'objectives' => [
            '인증, 세션, 인가의 역할을 각각 설명한다.',
            'ID를 추측할 수 있다는 사실보다 소유권 검사 누락이 핵심 원인임을 이해한다.',
            '수평 권한 상승을 요청과 SQL 관점에서 추적한다.',
        ],
        'lesson' => [
            'summary' => '학습 노트 · 문서 번호는 어느 행을 찾을지 알려 줄 뿐, 그 행을 볼 권한까지 증명하지 않습니다.',
            'paragraphs' => [
                'IDOR는 사용자가 전달한 객체 식별자를 서버가 직접 조회하면서 현재 사용자가 그 객체에 접근할 수 있는지 확인하지 않을 때 발생합니다. 숫자 ID, UUID, 파일명 모두 같은 문제가 생길 수 있습니다.',
                '취약한 쿼리는 WHERE id = ? 조건만 사용합니다. 안전한 쿼리는 같은 요청에서도 WHERE id = ? AND owner_id = ?처럼 현재 사용자와 자원의 관계를 함께 확인합니다.',
                '복잡하거나 무작위인 ID는 추측을 어렵게 만들 수 있지만 인가를 대신하지 않습니다. 로그, 링크, 공유 화면에서 ID가 노출될 수 있으므로 모든 객체 요청에서 서버 측 검사가 필요합니다.',
            ],
            'diagram' => '/assets/lessons/access-control.svg',
            'table' => [
                'columns' => ['단계', '취약한 처리', '안전한 처리'],
                'rows' => [
                    ['요청', 'GET /document?id=1002', '동일'],
                    ['조회', 'WHERE id = :id', 'WHERE id = :id AND owner = :viewer'],
                    ['판정', '행이 있으면 반환', '소유자 또는 명시적 공유 관계 확인'],
                    ['결과', '다른 사용자 문서 노출', '권한 없으면 404 또는 403'],
                ],
            ],
            'code' => [
                'language' => 'sql',
                'content' => "-- 취약한 조회\nSELECT title, body FROM documents WHERE id = :id;\n\n-- 안전한 조회\nSELECT title, body\nFROM documents\nWHERE id = :id AND owner_id = :current_user_id;",
            ],
        ],
        'resources' => [
            ['label' => 'PortSwigger · IDOR', 'url' => 'https://portswigger.net/web-security/access-control/idor'],
            ['label' => 'OWASP · Authorization Cheat Sheet', 'url' => 'https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html'],
        ],
        'hints' => [
            ['level' => 1, 'title' => '선택자는 어디에 있나', 'body' => '내 문서를 열었을 때 URL에서 어떤 값이 문서를 선택하는지 확인하세요.'],
            ['level' => 2, 'title' => '다른 번호의 흔적', 'body' => '페이지 아래 활동 로그에는 방금 공유가 해제된 문서 번호가 남아 있습니다.'],
            ['level' => 3, 'title' => '소유권 검사 확인', 'body' => 'id 값을 활동 로그에서 본 번호로 바꾸세요. 서버는 로그인만 확인하고 owner 조건을 쿼리에 넣지 않습니다.'],
        ],
        'lab' => ['type' => 'idor_sqlite'],
        'completion' => [
            'event' => 'foreign_document_viewed',
            'email' => [
                'subject' => '[Nova] 소유권 검사 누락 확인',
                'preview' => '객체 ID는 권한 증명이 아닙니다. 모든 조회에서 사용자와 자원의 관계를 확인해야 합니다.',
            ],
        ],
    ],
    [
        'id' => 'web-v1-04-sqli-login',
        'module' => '02-injection',
        'order' => 40,
        'title' => 'SQL 문장의 경계 무너뜨리기',
        'eyebrow' => '모듈 2 · 인젝션',
        'difficulty' => '초급',
        'minutes' => 35,
        'prerequisites' => ['web-v1-03-idor'],
        'client' => '코멧 재고 관리',
        'story' => '코멧 물류는 야간 상하차 현황을 StockFlow 포털에서 관리합니다. 퇴사한 용역 인력의 접속 시각과 겹치는 시간대에 manager 세션이 생성됐지만, 관리자 비밀번호 변경·재설정·정상 로그인 기록은 없었습니다. 오늘 22시 야간 출고를 앞두고 있어, 인증 우회가 재현되면 포털을 즉시 폐쇄하고 수기 승인 절차로 전환해야 합니다.',
        'brief' => '유효한 관리자 비밀번호를 제공받지 않은 외부 사용자 관점에서 Comet StockFlow 로그인 화면을 블랙박스 점검하세요. 브라우저나 로컬 프록시로 자신의 로그인 요청을 관찰하고, 수동 입력만으로 manager 세션이 발급되는지 확인하세요. 성공하면 입력값의 민감한 부분은 가리고 세션 역할과 최종 화면을 증거로 남기세요.',
        'target' => [
            'objective' => '유효한 관리자 비밀번호 없이 manager 세션을 발급받을 수 있음을 재현하고 인증 우회 증거를 확보하세요.',
            'entry_url' => '/comet/login',
            'service_name' => 'Comet StockFlow',
            'hostname' => 'night.comet-logistics.training',
            'entry_path' => '/login',
            'access_method' => '공개된 StockFlow 야간 운영자 로그인 화면 접속',
            'environment' => '야간 입출고 현황 서비스 · 검증 시간에는 재고 변경 기능 잠금',
            'surface' => '운영자 로그인 · 인증 오류 응답 · manager 세션 권한 경계',
        ],
        'email' => [
            'subject' => '[긴급 사고 재현] 정상 로그인 기록 없는 StockFlow manager 세션',
            'sender' => ['name' => '백승호', 'role' => '물류시스템 운영팀장', 'organization' => '코멧 물류', 'address' => 'seungho.baek@comet-logistics.training'],
            'urgency' => '긴급 · 오늘 22:00 야간 출고 시작 전 잠정 폐쇄 판단',
            'contact_context' => '인프라·물류 운영 책임자가 아래 로그인 자산에 대한 제한적 외부 검증을 승인했습니다. 실제 출고 정보는 검증 시간 동안 비식별 상태로 전환되며, 현재 필요한 것은 인증 우회 가능성의 1회 재현입니다.',
            'scope' => ['night.comet-logistics.training의 로그인 폼과 로그인 결과 화면만 대상', '자신의 요청 관찰과 수동 입력 변경·재전송 허용', '로그인 후 재고 수정·출고 승인·사용자 열거·다른 데이터 조회는 범위 외'],
            'deliverables' => ['유효한 관리자 자격 증명이 없음을 보여 주는 시작 조건', 'manager 세션이 발급된 최종 요청·응답과 역할 표시 화면', '인증 입력을 데이터로만 처리하고 서버에서 암호를 검증하도록 하는 우선 조치'],
            'cautions' => ['성공 후 manager 역할 확인 외의 변경 요청을 전송하지 마세요.', '자동화된 자격 증명 대입이나 서비스 가용성에 영향을 주는 입력은 사용하지 마세요.'],
            'closing' => '재현 여부가 확인되면 포털을 잠정 폐쇄하고 야간 출고를 수기 승인 절차로 전환할 예정입니다.',
            'cta_label' => 'Comet StockFlow 야간 로그인에 접속',
        ],
        'objectives' => [
            '문자열 연결이 입력값과 SQL 문법의 경계를 없애는 과정을 설명한다.',
            'boolean 조건과 SQL 주석이 인증 쿼리에 미치는 영향을 예측한다.',
            'prepared statement가 코드와 데이터를 분리하는 이유를 이해한다.',
        ],
        'lesson' => [
            'summary' => '학습 노트 · SQL Injection은 특수문자 자체가 아니라 입력값이 SQL 코드로 재해석되는 경계 실패입니다.',
            'paragraphs' => [
                '애플리케이션이 username과 password를 SQL 문자열 안에 직접 넣으면 사용자가 입력한 따옴표가 원래 문자열을 끝낼 수 있습니다. 그 뒤에 새로운 조건과 주석을 붙이면 쿼리의 의미가 바뀝니다.',
                '로그인 우회에서는 비밀번호 비교보다 우선하거나 전체 WHERE 절을 참으로 만드는 boolean 표현식을 구성합니다. 주석은 애플리케이션이 뒤에 붙인 따옴표와 조건을 무시하게 할 수 있습니다.',
                '방어는 입력 문자열을 블랙리스트로 지우는 것이 아니라 prepared statement에 값을 별도로 바인딩하는 것입니다. 그러면 따옴표와 연산자는 SQL 문법이 아니라 평범한 데이터로 처리됩니다.',
            ],
            'diagram' => '/assets/lessons/sql-injection.svg',
            'table' => [
                'columns' => ['입력 실험', '관찰할 변화', '학습 의미'],
                'rows' => [
                    ['정상 사용자 / 틀린 암호', '로그인 실패', '기본 쿼리 확인'],
                    ['따옴표 하나', 'SQLite 문법 오류', '문자열 경계 확인'],
                    ['항상 참인 OR 조건', '조건식 의미 변화', '데이터가 코드가 됨'],
                    ['주석 추가', '뒤의 암호 조건 제거', '남은 쿼리 정리'],
                ],
            ],
            'code' => [
                'language' => 'sql',
                'content' => <<<'SQL'
-- 취약한 문자열 연결 결과
SELECT id, username, role
FROM accounts
WHERE username = '$username' AND password = '$password';

-- 방어
SELECT id, username, role
FROM accounts
WHERE username = :username AND password_hash = :password_hash;
SQL,
            ],
        ],
        'resources' => [
            ['label' => 'PortSwigger · SQL Injection', 'url' => 'https://portswigger.net/web-security/sql-injection'],
            ['label' => 'OWASP · SQL Injection Prevention', 'url' => 'https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html'],
        ],
        'hints' => [
            ['level' => 1, 'title' => '쿼리 경계 찾기', 'body' => 'username에 따옴표 하나를 넣고 오류 메시지가 SQL 문자열의 어느 위치를 가리키는지 보세요.'],
            ['level' => 2, 'title' => '조건을 참으로 만들기', 'body' => 'manager 문자열 뒤에서 OR 연산으로 항상 참인 비교식을 추가하는 형태를 생각하세요.'],
            ['level' => 3, 'title' => '뒤쪽 조건 제거', 'body' => 'SQLite의 줄 주석을 사용해 애플리케이션이 덧붙이는 password 비교와 마지막 따옴표를 무시하세요.'],
        ],
        'lab' => ['type' => 'sqli_login'],
        'completion' => [
            'event' => 'manager_session_started',
            'email' => [
                'subject' => '[Comet] 야간 관리자 세션 생성됨',
                'preview' => '입력값이 SQL 문법으로 해석되면서 인증 조건이 무너졌습니다.',
            ],
        ],
    ],
    [
        'id' => 'web-v1-05-sqli-union',
        'module' => '02-injection',
        'order' => 50,
        'title' => 'UNION으로 숨은 행 꺼내기',
        'eyebrow' => '모듈 2 · 데이터 추출',
        'difficulty' => '중급',
        'minutes' => 45,
        'prerequisites' => ['web-v1-04-sqli-login'],
        'client' => '헬리오스 카탈로그',
        'story' => '헬리오스 산업유통은 B2B 고객에게 소모품 카탈로그를 공개합니다. 신규 상품 공개 점검 중 검색 결과 영역에 상품이 아닌 구매 승인 메모 일부가 나타났다는 신고가 접수됐습니다. 신고자는 로그인하지 않은 방문자였고, 메모에는 공급가 협상 정보가 포함될 수 있어 내일 카탈로그 공개 전에 비상품 데이터 노출 여부를 확인해야 합니다.',
        'brief' => '비회원 방문자 상태로 Helios Supply Catalog의 검색 기능을 블랙박스 점검하세요. 브라우저 개발자 도구나 로컬 프록시를 사용해 검색 요청과 오류 응답을 관찰할 수 있습니다. 공개 상품 정보가 아닌 지정된 내부 승인 메모 한 건을 검색 결과에서 재현하고, 그 이상 데이터는 열람하지 마세요.',
        'target' => [
            'objective' => '비회원 상품 검색 결과에 지정된 내부 승인 메모가 노출될 수 있음을 재현하고 응답 증거를 확보하세요.',
            'entry_url' => '/helios/products',
            'service_name' => 'Helios Supply Catalog',
            'hostname' => 'catalog.helios-supply.training',
            'entry_path' => '/products',
            'access_method' => '비회원으로 공개 상품 카탈로그와 검색 기능 접속',
            'environment' => '산업 소모품 B2B 카탈로그 · 주문과 고객 계약 기능은 별도 시스템',
            'surface' => '공개 상품 검색 · 오류 응답 · 상품과 내부 업무 데이터 경계',
        ],
        'email' => [
            'subject' => '[공개 전 진단] Helios 상품 검색을 통한 운영 메모 노출 가능성',
            'sender' => ['name' => '임나경', 'role' => '전자상거래 플랫폼 PO', 'organization' => '헬리오스 산업유통', 'address' => 'nakyung.lim@helios-supply.training'],
            'urgency' => '높음 · 내일 14:00 카탈로그 공개 회의 전 결과 필요',
            'contact_context' => '제품·법무팀은 내일 공개 여부를 결정하기 위해 실제 데이터 경계가 무너지는지 확인할 필요가 있습니다. 아래 공개 검색 자산에서 지정된 승인 메모 한 건까지의 읽기 전용 검증을 승인합니다.',
            'scope' => ['catalog.helios-supply.training의 비회원 상품 검색과 결과 화면만 대상', '검색 입력 변경, 자신의 요청 재전송, 오류 응답 관찰 허용', '데이터 수정·삭제, 구조 변경, 다른 내부 자료 열거, 자동화된 대량 요청은 범위 외'],
            'deliverables' => ['정상 상품 검색과 비정상 응답의 차이를 보여 주는 요청 기록', '지정된 승인 메모 한 건이 공개 결과에 표시된 응답과 화면 증거', '검색 입력의 안전한 처리, 오류 정보 제한, 데이터 접근 권한 축소 조치'],
            'cautions' => ['지정된 증거 한 건이 보이면 다른 내부 자료를 계속 탐색하지 마세요.', '자동화된 대량 대입이나 서비스 응답을 지연시키는 입력은 사용하지 마세요.'],
            'closing' => '재현이 성공하면 카탈로그 공개를 보류합니다. 내부 자료가 노출된 사실과 함께 오류 메시지 숨김만으로 해결되지 않는 이유를 보고해 주세요.',
            'cta_label' => 'Helios 상품 카탈로그에 접속',
        ],
        'objectives' => [
            'UNION으로 합치는 SELECT가 같은 열 개수와 호환 자료형을 가져야 함을 확인한다.',
            'NULL과 ORDER BY를 이용해 원래 결과의 형태를 추론한다.',
            '인젝션이 인증 우회를 넘어 데이터 유출로 이어지는 경로를 설명한다.',
        ],
        'lesson' => [
            'summary' => '학습 노트 · UNION 기반 SQLi는 원래 화면이 표시하는 열을 다른 테이블의 데이터를 운반하는 통로로 바꿉니다.',
            'paragraphs' => [
                'UNION은 두 SELECT의 결과 집합을 위아래로 합칩니다. 따라서 양쪽 SELECT의 열 개수가 같고 각 위치의 자료형이 호환되어야 합니다. 먼저 원래 쿼리의 모양을 알아내는 이유입니다.',
                'ORDER BY 번호를 늘려 오류가 나는 지점을 찾거나 UNION SELECT에 NULL을 하나씩 추가해 열 개수를 추론할 수 있습니다. NULL은 여러 자료형과 호환되어 구조를 시험하기에 편리합니다.',
                '실제 서비스에서는 DB 계정에 최소 권한을 주고, 상세 오류를 노출하지 않으며, 무엇보다 모든 사용자 입력을 prepared statement로 바인딩해야 합니다. 오류 비공개는 정보 노출을 줄이지만 안전한 쿼리 바인딩을 대신하지 않습니다.',
            ],
            'diagram' => '/assets/lessons/sql-injection.svg',
            'table' => [
                'columns' => ['단계', '목적', '성공 신호'],
                'rows' => [
                    ['열 개수 확인', '원래 SELECT의 폭 파악', '특정 ORDER BY 번호부터 오류'],
                    ['NULL 배치', 'UNION 결과 모양 맞춤', '검색 결과가 정상 렌더링'],
                    ['문자열 위치 확인', '화면에 표시되는 열 선택', '테스트 문자열 출력'],
                    ['내부 자료 1건 확인', '오류에서 확인한 승인 메모 조회', '운영 메모가 상품 행으로 표시'],
                ],
            ],
            'code' => [
                'language' => 'sql',
                'content' => "-- 원래 검색의 두 출력 열\nSELECT name, price\nFROM products\nWHERE name LIKE '%<입력값>%';\n\n-- 구조를 학습하기 위한 일반 예시\nUNION SELECT NULL, NULL\nUNION SELECT title, body FROM <내부_메모_테이블>",
            ],
        ],
        'resources' => [
            ['label' => 'PortSwigger · UNION attacks', 'url' => 'https://portswigger.net/web-security/sql-injection/union-attacks'],
            ['label' => 'OWASP · SQL Injection Prevention', 'url' => 'https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html'],
        ],
        'hints' => [
            ['level' => 1, 'title' => '결과의 폭', 'body' => 'ORDER BY 뒤 숫자를 늘려 보며 몇 번째 열에서 오류가 나는지 확인하세요.'],
            ['level' => 2, 'title' => 'NULL로 모양 맞추기', 'body' => '원래 SELECT는 두 열을 반환합니다. UNION SELECT에 같은 수의 NULL을 배치하세요.'],
            ['level' => 3, 'title' => '지정 메모 한 건', 'body' => '검색 오류와 응답에서 확인한 구매 승인 메모의 테이블·열 이름을 사용해, 의뢰가 지정한 한 건만 두 출력 위치에 맞추세요.'],
        ],
        'lab' => ['type' => 'union_sqlite'],
        'completion' => [
            'event' => 'training_note_extracted',
            'email' => [
                'subject' => '[Helios] 비공개 운영 메모가 검색됨',
                'preview' => '원래 검색 결과의 열을 이용해 다른 테이블의 행이 화면으로 이동했습니다.',
            ],
        ],
    ],
    [
        'id' => 'web-v1-06-reflected-xss',
        'module' => '02-injection',
        'order' => 60,
        'title' => '문자열이 브라우저 코드가 될 때',
        'eyebrow' => '모듈 2 · 브라우저 문맥',
        'difficulty' => '중급',
        'minutes' => 40,
        'prerequisites' => ['web-v1-05-sqli-union'],
        'client' => '프리즘 도움말',
        'story' => '프리즘케어는 고객센터 상담원이 사용하는 도움말 검색을 개편했습니다. 시범 운영 중 한 상담원이 협력사에서 받은 검색 링크를 열자 검색 결과 대신 낯선 화면 요소가 나타났고, 브라우저가 페이지 동작을 차단했다는 경고를 남겼습니다. 상담 화면은 고객 문의를 다루므로, 다음 주 전사 배포 전에 사용자가 전달한 검색어가 상담원 브라우저에서 의도치 않은 동작을 만들 수 있는지 확인해야 합니다.',
        'brief' => 'PrismCare Help Desk의 공개 지식베이스 검색을 블랙박스 방식으로 점검하세요. 브라우저 개발자 도구나 로컬 프록시로 검색 요청과 렌더링 결과를 관찰하고, 외부 통신이나 데이터 접근 없이 페이지 안에 무해한 검증 표식이 나타나도록 재현하세요. 성공 후에는 추가 동작을 시도하지 마세요.',
        'target' => [
            'objective' => '사용자가 제어하는 검색어가 상담원 브라우저에서 무해한 검증 동작을 일으킬 수 있음을 재현하고 화면·콘솔 증거를 확보하세요.',
            'entry_url' => '/prism/search',
            'service_name' => 'PrismCare Help Desk',
            'hostname' => 'help.prismcare.training',
            'entry_path' => '/search',
            'access_method' => '공개된 PrismCare 도움말 검색 화면 접속',
            'environment' => '상담원 지식베이스 · 고객 문의와 상담 계정 시스템은 연결되지 않음',
            'surface' => '도움말 검색 · 결과 렌더링 · 브라우저 실행 문맥',
        ],
        'email' => [
            'subject' => '[배포 보류] PrismCare 도움말 검색어의 HTML 실행 의심',
            'sender' => ['name' => '송다인', 'role' => 'CX 플랫폼 개편 TF 리드', 'organization' => '프리즘케어 고객센터', 'address' => 'dain.song@prismcare.training'],
            'urgency' => '긴급 · 오늘 18:00 상담원 전체 배포 전 재현 필요',
            'contact_context' => '배포는 현재 중단된 상태이며 제품·개인정보보호팀이 아래 공개 검색 자산에 대한 제한적 검증을 승인했습니다. 고객 문의 데이터는 이 검색 서비스와 분리되어 있으므로 브라우저 내 무해한 실행 가능성까지만 확인해 주세요.',
            'scope' => ['help.prismcare.training의 도움말 검색과 결과 화면만 대상', '자신의 검색 요청 변경, 개발자 도구 관찰, 로컬에서 확인 가능한 무해한 검증 동작 허용', '외부 통신·원격 코드, 쿠키나 저장소 열람, 피싱 화면, 지속성 있는 변경은 범위 외'],
            'deliverables' => ['일반 검색 결과와 비정상 렌더링 결과를 비교한 요청·화면 기록', '외부 통신 없이 무해한 검증 동작이 발생한 화면 또는 콘솔 증거', '출력 위치에 맞는 인코딩, 안전한 DOM 생성, 브라우저 보조 통제에 대한 조치'],
            'cautions' => ['검증 표식 확인에 필요하지 않은 스크립트 동작은 사용하지 마세요.', '외부 URL·원격 스크립트·브라우저 저장 정보에 접근하지 마세요.'],
            'closing' => '재현 결과에는 검색어가 화면 표시를 넘어 브라우저 동작으로 해석됐는지, 상담원에게 미칠 수 있는 영향과 근본 조치를 정리해 주세요.',
            'cta_label' => 'PrismCare 도움말 검색에 접속',
        ],
        'objectives' => [
            '사용자 입력이 놓이는 HTML 문맥에 따라 필요한 인코딩이 달라짐을 이해한다.',
            'HTML 파서가 문자열을 DOM과 실행 가능한 이벤트로 바꾸는 과정을 관찰한다.',
            '출력 인코딩, 안전한 DOM API, CSP가 서로 보완하는 방어임을 설명한다.',
        ],
        'lesson' => [
            'summary' => '학습 노트 · XSS는 서버에서 만들어진 문자열이 브라우저의 코드 문맥으로 들어가 피해자의 권한에서 실행되는 문제입니다.',
            'paragraphs' => [
                'HTML 본문, 속성, URL, JavaScript 문자열은 서로 다른 파싱 규칙을 사용합니다. 한 문맥에서 안전한 인코딩이 다른 문맥에서는 충분하지 않을 수 있으므로 데이터를 삽입하는 위치를 먼저 알아야 합니다.',
                'innerHTML이나 템플릿 문자열로 입력을 합치면 브라우저는 꺾쇠괄호와 속성을 마크업으로 해석합니다. textContent처럼 텍스트 전용 API를 사용하면 같은 입력이 실행 가능한 DOM으로 바뀌지 않습니다.',
                'XSS를 검증할 때는 외부 통신이나 저장 정보 접근 대신 현재 문서에 식별 가능한 표식을 남기는 무해한 증명을 사용합니다. 목표는 브라우저가 입력을 코드로 해석했다는 사실을 확인하는 것이지 추가 권한을 행사하는 것이 아닙니다.',
            ],
            'diagram' => '/assets/lessons/xss-context.svg',
            'table' => [
                'columns' => ['출력 위치', '취약한 예', '권장 방식'],
                'rows' => [
                    ['HTML 본문', 'element.innerHTML = input', 'textContent 또는 HTML entity encoding'],
                    ['HTML 속성', 'value="입력" 직접 결합', '속성 API와 문맥별 encoding'],
                    ['URL', 'href에 임의 scheme 허용', '허용 scheme 검사와 URL 파서'],
                    ['JavaScript', 'script 문자열에 직접 삽입', '데이터를 JSON으로 전달하고 코드와 분리'],
                ],
            ],
            'code' => [
                'language' => 'html',
                'content' => "<!-- 취약한 렌더링 개념 -->\n<div>검색 결과: <사용자 입력></div>\n\n<!-- 안전한 렌더링 개념 -->\n<script nonce=\"...\">\n  result.textContent = userInput;\n</script>",
            ],
        ],
        'resources' => [
            ['label' => 'PortSwigger · Cross-site scripting', 'url' => 'https://portswigger.net/web-security/cross-site-scripting'],
            ['label' => 'OWASP · XSS Prevention Cheat Sheet', 'url' => 'https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html'],
        ],
        'hints' => [
            ['level' => 1, 'title' => '출력 문맥 확인', 'body' => '검색어에 단순한 HTML 태그를 넣고 결과가 텍스트인지 실제 요소인지 확인하세요.'],
            ['level' => 2, 'title' => '자동으로 발생하는 이벤트', 'body' => '로드에 실패하는 이미지 요소는 브라우저 이벤트를 발생시킬 수 있습니다.'],
            ['level' => 3, 'title' => '무해한 실행 증거', 'body' => '외부 요청이나 저장 정보 접근 없이 현재 페이지의 제목·속성처럼 로컬에서 확인 가능한 표식만 바꾸고, Elements 또는 Console에서 결과를 기록하세요.'],
        ],
        'lab' => ['type' => 'xss_nonce'],
        'completion' => [
            'event' => 'sandbox_script_executed',
            'email' => [
                'subject' => '[Prism] 검색 결과 문맥 탈출 감지',
                'preview' => '문자열이 HTML 요소와 이벤트로 해석되었습니다. 출력 위치에 맞는 인코딩이 필요합니다.',
            ],
        ],
    ],
    [
        'id' => 'web-v1-07-path-traversal',
        'module' => '03-server-boundaries',
        'order' => 70,
        'title' => '파일 경로의 울타리 넘기',
        'eyebrow' => '모듈 3 · 파일시스템 경계',
        'difficulty' => '초급',
        'minutes' => 35,
        'prerequisites' => ['web-v1-06-reflected-xss'],
        'client' => '아틀라스 현장 매뉴얼',
        'story' => '아틀라스 에너지는 현장 기사가 설비 매뉴얼을 열어 보는 Field Manual 포털을 운영합니다. 한 기사가 모바일 즐겨찾기의 오래된 링크를 열었을 때 배정된 설비 매뉴얼이 아닌 제한 등급의 점검 기록 일부가 표시됐다고 보고했습니다. 기록에는 설비 위치와 정비 일정이 포함될 수 있어, 다음 현장 교대 전 공개 문서 뷰어의 파일 접근 경계를 확인해야 합니다.',
        'brief' => '일반 현장 기사 권한으로 Atlas Field Manual을 블랙박스 점검하세요. 브라우저 개발자 도구나 로컬 프록시에서 정상 매뉴얼 열람 요청을 관찰하고, 의뢰가 지정한 제한 점검 기록 한 건이 같은 뷰어를 통해 반환되는지 확인하세요. 지정 기록 이외의 파일은 탐색하지 마세요.',
        'target' => [
            'objective' => '일반 기사 권한으로 지정된 제한 점검 기록을 열 수 있음을 재현하고 최종 요청·응답 증거를 확보하세요.',
            'entry_url' => '/atlas/viewer',
            'service_name' => 'Atlas Field Manual',
            'hostname' => 'manuals.atlas-field.training',
            'entry_path' => '/viewer',
            'access_method' => '일반 현장 기사에게 공개된 매뉴얼 목록과 문서 뷰어 접속',
            'environment' => '설비 매뉴얼 서비스 · 작업지시와 설비 제어 시스템은 별도 운영',
            'surface' => '매뉴얼 목록 · 문서 뷰어 · 공개 문서와 제한 점검 기록의 접근 경계',
        ],
        'email' => [
            'subject' => '[현장 포털 점검] Atlas Field Manual 비공개 점검 파일 노출 의심',
            'sender' => ['name' => '강태오', 'role' => '현장 IT·설비자료 관리자', 'organization' => '아틀라스 에너지', 'address' => 'taeo.kang@atlas-field.training'],
            'urgency' => '보통 이상 · 다음 월요일 현장 태블릿 업데이트 전 조치',
            'contact_context' => '현장 운영·안전관리 책임자가 아래 문서 자산에서 읽기 전용 검증을 승인했습니다. 설비 제어와 작업지시 시스템은 분리되어 있으며, 지정된 점검 기록 한 건이 열리는지까지만 확인하면 됩니다.',
            'scope' => ['manuals.atlas-field.training의 매뉴얼 목록과 문서 열람 기능만 대상', '정상 열람 요청의 관찰과 화면에 드러난 참조값을 이용한 수동 요청 변경 허용', '지정되지 않은 파일 열거, 절대 경로·시스템 파일 시도, 자동화 탐색은 범위 외'],
            'deliverables' => ['일반 기사에게 허용된 공개 매뉴얼의 정상 열람 기록', '지정된 제한 점검 기록이 반환된 요청·응답과 등급 표시 화면', '서버가 허용 문서만 선택하도록 식별자 매핑과 최종 경계를 확인하는 조치'],
            'cautions' => ['의뢰에 지정된 제한 점검 기록 한 건만 확인하세요.', '시스템 파일명을 추측하거나 다른 경로를 연속해서 시도하지 마세요.'],
            'closing' => '현장에서는 고정된 즐겨찾기가 오래 남아 있을 수 있으므로, 파일이 없을 때의 처리와 경로 검증을 같이 권고해 주세요.',
            'cta_label' => 'Atlas Field Manual 문서 뷰어에 접속',
        ],
        'objectives' => [
            '상대 경로의 점 구간이 파일시스템에서 어떻게 정규화되는지 설명한다.',
            '문자열 prefix 검사와 canonical path 검사의 차이를 이해한다.',
            '허용 루트와 공개 하위 폴더를 별도로 검증해야 함을 확인한다.',
        ],
        'lesson' => [
            'summary' => '학습 노트 · 파일명을 경로에 그대로 붙이면 사용자가 의도한 공개 폴더 밖의 파일을 선택할 수 있습니다.',
            'paragraphs' => [
                '점 두 개와 슬래시는 현재 디렉터리의 부모로 이동합니다. 공개 문서 경로에 부모 이동 구간이 포함되면 정규화된 최종 위치가 제한 문서 영역으로 바뀔 수 있습니다.',
                '안전한 구현은 허용된 논리 이름을 실제 파일에 매핑하거나, realpath로 정규화한 최종 경로가 허용 루트 안에 있는지 디렉터리 경계를 포함해 확인합니다. 단순히 ../ 문자열 한 종류만 지우면 중첩 인코딩과 플랫폼 차이를 놓칠 수 있습니다.',
                '승인된 검증에서는 의뢰가 지정한 제한 문서 한 건을 확인한 뒤 멈춰야 합니다. 운영체제 파일이나 다른 서비스 경로까지 탐색하는 행동은 같은 기법을 쓰더라도 승인 범위를 벗어납니다.',
            ],
            'diagram' => '/assets/lessons/filesystem-boundary.svg',
            'table' => [
                'columns' => ['입력', '정규화 결과', '판정'],
                'rows' => [
                    ['guide.txt', '/srv/manuals/public/guide.txt', '공개 문서'],
                    ['manual/intro.txt', '/srv/manuals/public/manual/intro.txt', '공개 하위 폴더'],
                    ['../restricted/inspection.txt', '/srv/manuals/restricted/inspection.txt', '제한 문서 경계 확인'],
                    ['../../outside.txt', '/srv 밖의 경로', '승인 범위 밖이므로 시도 금지'],
                ],
            ],
            'code' => [
                'language' => 'php',
                'content' => <<<'PHP'
// 취약한 개념
$path = $manualRoot . '/public/' . $_GET['file'];
$content = file_get_contents($path);

// 안전한 개념
$resolved = realpath($candidate);
assert(path_is_within($resolved, $allowedPublicRoot));
PHP,
            ],
        ],
        'resources' => [
            ['label' => 'PortSwigger · Path traversal', 'url' => 'https://portswigger.net/web-security/file-path-traversal'],
            ['label' => 'OWASP · Input Validation Cheat Sheet', 'url' => 'https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html'],
        ],
        'hints' => [
            ['level' => 1, 'title' => '기준 디렉터리 찾기', 'body' => '정상 매뉴얼을 열고 개발자 도구나 프록시에서 문서를 선택하는 요청 값과 공개 문서의 기준 위치를 확인하세요.'],
            ['level' => 2, 'title' => '제한 문서 참조', 'body' => '공개 매뉴얼의 응답과 화면에서 의뢰가 지정한 점검 기록의 상대 위치를 확인하고, 정상 문서의 기준 위치와 비교하세요.'],
            ['level' => 3, 'title' => '최종 경로 확인', 'body' => '문서 선택 값을 수동으로 재전송해 정규화된 위치가 공개 영역을 벗어나는지 확인하세요. 지정 기록 한 건이 열리면 즉시 중단하세요.'],
        ],
        'lab' => ['type' => 'path_traversal'],
        'completion' => [
            'event' => 'private_proof_read',
            'email' => [
                'subject' => '[Atlas] 비공개 점검 파일 열람됨',
                'preview' => '상대 경로가 공개 폴더의 울타리를 넘었습니다. 정규화한 최종 경로를 검증해야 합니다.',
            ],
        ],
    ],
    [
        'id' => 'web-v1-08-upload-validation',
        'module' => '03-server-boundaries',
        'order' => 80,
        'title' => '업로드 파일의 세 가지 얼굴',
        'eyebrow' => '모듈 3 · 업로드 검증',
        'difficulty' => '중급',
        'minutes' => 45,
        'prerequisites' => ['web-v1-07-path-traversal'],
        'client' => '픽셀펫 프로필',
        'story' => '픽셀펫은 반려동물 프로필 서비스의 아바타 업로더를 새로 만들었습니다. 콘텐츠 모니터링에서 이미지로 승인된 파일 하나가 실제로는 이미지 디코더가 읽을 수 없는 형식이라는 경보가 발생했습니다. 아직 공개 프로필에서 실행되거나 배포된 정황은 없지만, 허용되지 않은 파일이 저장될 수 있다면 서비스 변조와 악성 콘텐츠 배포로 이어질 수 있어 정식 출시 전 검증이 필요합니다.',
        'brief' => '제공된 PixelPet 계정으로 아바타 업로드 기능을 블랙박스 점검하세요. 브라우저 개발자 도구나 로컬 프록시에서 자신의 업로드 요청을 관찰·변경할 수 있습니다. 실행 코드가 아닌 의뢰용 무해 표식만 담긴 비이미지 파일이 이미지로 승인되는지 확인하고 저장 승인 영수증을 확보하세요.',
        'target' => [
            'objective' => '허용된 이미지가 아닌 무해한 파일을 아바타로 승인받을 수 있음을 재현하고 저장 영수증을 확보하세요.',
            'entry_url' => '/pixelpet/avatar',
            'service_name' => 'PixelPet Profile',
            'hostname' => 'profile.pixelpet.training',
            'entry_path' => '/avatar',
            'access_method' => '의뢰용 PixelPet 회원 계정으로 프로필과 아바타 업로드 화면 접속',
            'environment' => '반려동물 프로필 서비스 · 검증 시간에는 새 아바타의 공개 노출 보류',
            'surface' => '아바타 선택 · 파일 업로드 요청 · 이미지 승인과 저장 정책',
        ],
        'email' => [
            'subject' => '[출시 전 검증] PixelPet이 비이미지 파일을 아바타로 승인한 경보',
            'sender' => ['name' => '오유진', 'role' => '프로필·미디어 제품 매니저', 'organization' => '픽셀펫 랩스', 'address' => 'yujin.oh@pixelpet.training'],
            'urgency' => '높음 · 아바타 업로드 재개 전 승인 조건 확인',
            'contact_context' => '제품·콘텐츠 안전팀이 아래 계정과 업로드 기능에 대한 제한적 검증을 승인했습니다. 검증 시간 동안 새 아바타는 공개 프로필에 배포되지 않으며, 비이미지 파일 승인 여부까지만 확인해 주세요.',
            'scope' => ['제공된 계정의 profile.pixelpet.training 아바타 업로드와 결과 영수증만 대상', '자신의 업로드 요청 관찰·수동 변경과 의뢰용 무해 표식 파일 사용 허용', '실행 코드·대용량 파일·제3자 콘텐츠 업로드, 공개 URL 호출, 저장 파일 실행 시도는 범위 외'],
            'deliverables' => ['제출 파일이 실제 이미지가 아님을 확인할 수 있는 로컬 정보', '서비스가 해당 파일을 이미지로 승인한 요청·응답과 저장 영수증', '파일 내용 검증, 안전한 재인코딩, 비공개 비실행 저장과 임의 이름 적용 조치'],
            'cautions' => ['파일 본문에는 지정된 무해 표식만 넣고 실행 가능한 코드를 작성하지 마세요.', '승인 이후 저장 파일의 공개 주소를 찾거나 실행하려고 시도하지 마세요.'],
            'closing' => '이 검증의 성공 기준은 코드 실행이 아니라 허용되지 않은 파일이 이미지 정책을 통과했다는 사실입니다. 승인 영수증을 확보하면 즉시 중단해 주세요.',
            'cta_label' => 'PixelPet 아바타 업로더에 접속',
        ],
        'objectives' => [
            '파일명, 요청 MIME, 서버 탐지 MIME, 실제 내용이 독립적인 신호임을 설명한다.',
            '클라이언트가 보낸 Content-Type을 단독 신뢰하면 안 되는 이유를 확인한다.',
            '검증 후 이름 재생성, 크기 제한, 비공개 저장, 실행 금지를 방어 순서로 연결한다.',
        ],
        'lesson' => [
            'summary' => '학습 노트 · 업로드 보안은 확장자 하나를 검사하는 문제가 아니라 입력 검증과 저장·서비스 방식을 함께 설계하는 문제입니다.',
            'paragraphs' => [
                'multipart 요청의 Content-Type은 브라우저나 프록시가 작성하므로 사용자가 바꿀 수 있습니다. image/png라고 선언해도 실제 바이트가 PNG라는 보장은 없습니다.',
                '서버는 필요한 파일 형식을 allowlist로 제한하고, 확장자와 magic bytes를 함께 검사하며, 원래 파일명을 버리고 무작위 저장명을 사용해야 합니다. 파일 크기와 이미지 디코딩 성공 여부도 검증해야 합니다.',
                '가장 중요한 마지막 경계는 업로드 디렉터리를 public web root 밖에 두고 실행 권한을 주지 않는 것입니다. 파일 검증이 실패하더라도 저장과 제공 단계에서 실행을 막는 다층 방어가 필요합니다.',
            ],
            'diagram' => '/assets/lessons/filesystem-boundary.svg',
            'table' => [
                'columns' => ['신호', '누가 정하는가', '단독 신뢰 가능'],
                'rows' => [
                    ['원본 filename', '클라이언트', '아니오'],
                    ['multipart Content-Type', '클라이언트', '아니오'],
                    ['서버가 탐지한 magic bytes', '서버', '다른 검사와 함께 사용'],
                    ['저장 위치와 실행 설정', '서버 운영 정책', '핵심 방어 경계'],
                ],
            ],
            'code' => [
                'language' => 'http',
                'content' => "POST /pixelpet/avatar HTTP/1.1\nHost: profile.pixelpet.training\nContent-Type: multipart/form-data; boundary=BOUNDARY\n\n--BOUNDARY\nContent-Disposition: form-data; name=\"avatar\"; filename=\"pet.png\"\nContent-Type: image/png\n\n<file bytes>\n--BOUNDARY--",
            ],
        ],
        'resources' => [
            ['label' => 'PortSwigger · File upload vulnerabilities', 'url' => 'https://portswigger.net/web-security/file-upload'],
            ['label' => 'OWASP · File Upload Cheat Sheet', 'url' => 'https://cheatsheetseries.owasp.org/cheatsheets/File_Upload_Cheat_Sheet.html'],
        ],
        'hints' => [
            ['level' => 1, 'title' => '두 종류의 타입', 'body' => '업로드 결과에서 filename 확장자와 multipart Content-Type이 각각 어떻게 기록되는지 비교하세요.'],
            ['level' => 2, 'title' => '요청을 수정하기', 'body' => '브라우저에서 전송한 multipart 요청을 편집해 파일 part의 Content-Type만 바꿀 수 있습니다.'],
            ['level' => 3, 'title' => '서버 판단 비교', 'body' => '의뢰용 무해 표식 파일의 이름과 본문은 그대로 두고, 프록시에서 업로드 파트가 선언하는 형식만 허용된 이미지 형식으로 바꿔 승인 결과를 비교하세요.'],
        ],
        'lab' => ['type' => 'upload_mime'],
        'completion' => [
            'event' => 'dangerous_upload_accepted',
            'email' => [
                'subject' => '[PixelPet] 아바타 MIME 불일치 감지',
                'preview' => '클라이언트가 선언한 이미지 타입만 믿어 스크립트 확장자 파일을 수락했습니다.',
            ],
        ],
    ],
    [
        'id' => 'web-v1-09-jwt-validation',
        'module' => '03-server-boundaries',
        'order' => 90,
        'title' => 'JWT의 점 세 개와 서명',
        'eyebrow' => '모듈 3 · 토큰 무결성',
        'difficulty' => '중급',
        'minutes' => 45,
        'prerequisites' => ['web-v1-08-upload-validation'],
        'client' => '벡터 배포 콘솔',
        'story' => '벡터클라우드는 고객사 앱의 배포 승인을 Deploy Gate에서 처리합니다. 토큰 처리 모듈을 교체한 뒤 관리자 역할이 없는 릴리스 담당자가 admin 승인 화면을 열었다는 감사 기록이 발견됐습니다. 계정 역할 변경이나 서명 키 유출 흔적은 없으며, 배포 실행 직전에 정책 엔진이 요청을 차단했습니다. 신규 모듈 배포를 중단한 상태에서 권한 검증 우회 여부를 긴급 확인해야 합니다.',
        'brief' => '제공된 viewer 계정으로 Vector Deploy Gate를 블랙박스 점검하세요. 브라우저 개발자 도구나 로컬 프록시에서 이 서비스가 자신의 세션에 사용하는 접근 증표를 관찰할 수 있습니다. 계정의 정식 역할을 변경하지 않고 admin 전용 승인 화면에 도달할 수 있는지 확인하고, 실제 배포 작업은 실행하지 마세요.',
        'target' => [
            'objective' => 'viewer 계정으로 admin 전용 배포 승인 화면에 접근할 수 있음을 재현하고 계정 역할·최종 응답 증거를 확보하세요.',
            'entry_url' => '/vector/approvals',
            'service_name' => 'Vector Deploy Gate',
            'hostname' => 'deploy.vector-cloud.training',
            'entry_path' => '/approvals',
            'access_method' => '의뢰용 viewer 계정으로 Deploy Gate 승인 현황 화면 접속',
            'environment' => '고객사 배포 승인 서비스 · 검증 시간에는 모든 실제 배포 실행 잠금',
            'surface' => 'viewer 세션 · 배포 승인 목록 · admin 권한 경계',
        ],
        'email' => [
            'subject' => '[긴급 권한 검증] viewer 계정의 Deploy Gate admin 화면 접근 기록',
            'sender' => ['name' => '윤지훈', 'role' => '클라우드 배포 안전성 책임자', 'organization' => '벡터클라우드', 'address' => 'jihoon.yoon@vector-cloud.training'],
            'urgency' => '긴급 · 신규 토큰 검증기 전체 배포 중단 상태',
            'contact_context' => '의심 세션은 폐기했고 실제 배포 실행은 모두 잠갔습니다. 보안·플랫폼 책임자가 아래 viewer 계정과 승인 화면에서 자신의 요청에 포함된 서비스 접근 증표를 조사하는 제한적 검증을 승인합니다.',
            'scope' => ['deploy.vector-cloud.training의 viewer 세션과 읽기 전용 승인 현황·admin 승인 화면만 대상', '자신의 서비스 접근 증표 관찰과 수동 요청 변경·재전송 허용', 'Hanplanet 계정 토큰·서명 키·다른 사용자 세션 조사, 승인 처리와 실제 배포 실행은 범위 외'],
            'deliverables' => ['검증 시작 시점의 계정 식별자와 viewer 역할', 'admin 승인 화면이 열린 최종 요청·응답 및 역할 불일치 증거', '서버가 허용한 검증 방식과 필수 권한·대상·만료 조건을 독립적으로 강제하는 조치'],
            'cautions' => ['Hanplanet 로그인이나 다른 서비스의 인증 정보를 조사에 사용하지 마세요.', 'admin 화면이 열리면 승인 버튼을 누르거나 실제 배포 동작을 시도하지 마세요.'],
            'closing' => '재현이 성공하면 신규 모듈을 롤백하고 관련 세션을 다시 폐기합니다. 권한 없는 사용자가 admin 화면에 도달한 증거와 영향 범위를 즉시 제출해 주세요.',
            'cta_label' => 'Vector Deploy Gate 승인 콘솔에 접속',
        ],
        'objectives' => [
            'JWT의 header, payload, signature 각 부분의 역할을 설명한다.',
            'Base64URL 인코딩이 기밀성과 무결성을 제공하지 않음을 확인한다.',
            '허용 algorithm 고정, 서명 검증, exp·aud·iss 검증을 방어 항목으로 연결한다.',
        ],
        'lesson' => [
            'summary' => '학습 노트 · JWT payload는 숨겨진 정보가 아니며, 서버가 신뢰할 수 있는 이유는 올바른 서명을 검증했기 때문입니다.',
            'paragraphs' => [
                'JWT는 보통 점으로 구분된 header, payload, signature로 구성됩니다. 앞의 두 부분은 Base64URL JSON이므로 토큰을 가진 누구나 읽을 수 있고 새 값으로 다시 인코딩할 수도 있습니다.',
                '서버는 자신이 허용한 algorithm과 키로 signature를 검증한 뒤에만 claim을 신뢰해야 합니다. 토큰 header가 선택한 임의 algorithm을 그대로 받아들이거나 none을 허용하면 공격자가 role 같은 claim을 바꿀 수 있습니다.',
                '점검 대상 서비스의 업무 토큰과 사이트 로그인 토큰은 목적과 audience가 다릅니다. 다른 서비스의 토큰이나 서명 키를 가져오지 말고, 승인된 대상이 자신의 세션에 발급한 증표만 관찰해야 합니다.',
            ],
            'diagram' => '/assets/lessons/server-trust-chain.svg',
            'table' => [
                'columns' => ['부분', '내용', '보안 성질'],
                'rows' => [
                    ['Header', 'alg, typ', '검증 방식을 설명하지만 스스로 신뢰할 수 없음'],
                    ['Payload', 'sub, role, aud, exp', '읽고 수정할 수 있는 claim'],
                    ['Signature', 'header와 payload에 대한 검증값', '키와 algorithm을 올바르게 검증할 때 무결성 제공'],
                    ['서버 정책', '허용 alg, aud, iss, exp', '토큰의 사용 범위를 최종 결정'],
                ],
            ],
            'code' => [
                'language' => 'json',
                'content' => "Header\n{\"alg\":\"none\",\"typ\":\"JWT\"}\n\nPayload\n{\"sub\":\"release-viewer\",\"role\":\"viewer\",\"aud\":\"vector-deploy\",\"scope\":\"deploy-approvals\"}\n\n서버는 header가 제안한 방식과 무관하게 허용 알고리즘·서명·claim을 모두 검증해야 합니다.",
            ],
        ],
        'resources' => [
            ['label' => 'PortSwigger · JWT attacks', 'url' => 'https://portswigger.net/web-security/jwt'],
            ['label' => 'OWASP · JWT Cheat Sheet', 'url' => 'https://cheatsheetseries.owasp.org/cheatsheets/JSON_Web_Token_for_Java_Cheat_Sheet.html'],
        ],
        'hints' => [
            ['level' => 1, 'title' => '점으로 나누기', 'body' => '토큰을 점 기준으로 나누고 첫 번째와 두 번째 부분을 Base64URL 디코딩하세요.'],
            ['level' => 2, 'title' => '신뢰되는 claim', 'body' => '배포 승인 화면이 어떤 role, audience, scope를 기대하는지 원본 증표와 정상 요청을 비교하세요. 권한과 무관한 대상·범위 값은 원래 세션과 일치해야 합니다.'],
            ['level' => 3, 'title' => '무서명 토큰 형태', 'body' => 'header의 alg를 none으로, payload role을 admin으로 바꾸고 두 부분을 Base64URL로 인코딩한 뒤 마지막 점까지 포함하세요.'],
        ],
        'lab' => ['type' => 'jwt_none'],
        'completion' => [
            'event' => 'admin_token_accepted',
            'email' => [
                'subject' => '[Vector] 서명 없는 관리자 토큰 승인됨',
                'preview' => 'payload가 아니라 서명과 서버 정책이 토큰의 무결성을 만듭니다.',
            ],
        ],
    ],
    [
        'id' => 'web-v1-10-ssrf',
        'module' => '03-server-boundaries',
        'order' => 100,
        'title' => '서버의 눈으로 내부 주소 보기',
        'eyebrow' => '모듈 3 · 네트워크 경계',
        'difficulty' => '중급',
        'minutes' => 45,
        'prerequisites' => ['web-v1-09-jwt-validation'],
        'client' => '루멘 이미지 프록시',
        'story' => '루멘 스튜디오는 마케팅 카드 URL을 등록하면 서버가 이미지를 가져와 보여 주는 Campaign Preview를 운영합니다. 한 캠페인 미리보기 결과에 외부에서 공개하지 않은 인프라 상태 문구가 표시됐고, 같은 시각 미리보기 worker가 내부 자산에 접근한 기록이 남았습니다. 외부 캠페인 업로드를 중단한 상태에서 사용자가 입력한 URL을 통해 내부 정보가 반환될 수 있는지 6시간 안에 확인해야 합니다.',
        'brief' => '캠페인 운영자 권한으로 Lumen Campaign Preview를 블랙박스 점검하세요. 브라우저 개발자 도구나 로컬 프록시에서 카드 등록 요청과 서버의 가져오기 결과를 관찰할 수 있습니다. 정상 카드에서 확인 가능한 단서만 사용해 의뢰가 지정한 내부 canary 응답이 미리보기 화면에 반환되는지 확인하세요.',
        'target' => [
            'objective' => '외부 사용자가 등록한 카드 URL을 통해 지정된 내부 canary 응답을 미리보기 화면에서 확인할 수 있음을 재현하세요.',
            'entry_url' => '/lumen/cards',
            'service_name' => 'Lumen Campaign Preview',
            'hostname' => 'preview.lumen-studio.training',
            'entry_path' => '/cards',
            'access_method' => '의뢰용 캠페인 운영자 계정으로 카드 등록·미리보기 화면 접속',
            'environment' => '마케팅 카드 미리보기 서비스 · 게시와 외부 캠페인 전송 기능은 검증 시간 동안 중단',
            'surface' => '카드 URL 등록 · 서버 측 미리보기 요청 · 공개 자산과 내부 서비스의 네트워크 경계',
        ],
        'email' => [
            'subject' => '[긴급 인프라 점검] Campaign Preview에 내부 상태 정보가 표시된 사고',
            'sender' => ['name' => '이로하', 'role' => '마케팅 플랫폼 SRE', 'organization' => '루멘 스튜디오', 'address' => 'roha.lee@lumen-studio.training'],
            'urgency' => '높음 · 외부 캠페인 업로드는 중단, 6시간 내 영향 판단',
            'contact_context' => 'SRE·법무 책임자가 아래 미리보기 자산과 읽기 전용 내부 canary에 대한 제한적 검증을 승인했습니다. canary 이외의 내부 서비스에는 접근하지 말고, 정상 카드 응답에서 직접 확인한 정보만 사용해 주세요.',
            'scope' => ['preview.lumen-studio.training의 카드 등록·미리보기와 지정된 읽기 전용 canary만 대상', '자신의 URL 입력 변경, 요청 재전송, 미리보기 응답 관찰 허용', 'localhost·임의 IP·클라우드 관리 주소·다른 내부 host, 포트 스캔, 자동화 탐색은 범위 외'],
            'deliverables' => ['브라우저 요청과 미리보기 서버의 후속 요청을 구분할 수 있는 기록', '지정된 내부 canary 응답이 화면에 반환된 요청·응답 증거', '허용 scheme·host·최종 연결 주소 검증, redirect 재검증과 outbound 정책 조치'],
            'cautions' => ['지정된 canary 응답이 보이면 다른 내부 주소를 시도하지 마세요.', '인터넷의 제3자 서버나 로컬 네트워크를 스캔하지 마세요.'],
            'closing' => '재현 결과는 입력 URL 검증만이 아니라 최종 연결 주소와 네트워크 egress 정책을 함께 설계하는 근거로 사용하겠습니다.',
            'cta_label' => 'Lumen Campaign Preview 운영 화면에 접속',
        ],
        'objectives' => [
            'SSRF에서 요청 주체가 사용자 브라우저가 아니라 취약한 서버임을 설명한다.',
            '내부 서비스와 metadata endpoint가 외부에서 보이지 않아도 보호가 필요한 이유를 이해한다.',
            'scheme·host allowlist, DNS 재검증, redirect 제한, egress 통제를 방어로 연결한다.',
        ],
        'lesson' => [
            'summary' => '학습 노트 · 서버가 사용자가 고른 URL을 대신 요청하면 사용자는 서버의 네트워크 위치와 권한을 빌릴 수 있습니다.',
            'paragraphs' => [
                '이미지 프록시, 웹훅 검사, 링크 미리보기처럼 서버가 URL을 가져오는 기능은 흔합니다. URL 전체를 사용자가 결정하면 서버 자신이나 내부 호스트로 요청을 보낼 수 있습니다.',
                '문자열 prefix만 검사하면 사용자 정보 구간, 대소문자, IP 표현, DNS 변경, redirect 같은 URL 해석 차이로 우회될 수 있습니다. 파싱한 scheme과 hostname을 정책에 맞게 검증하고 최종 연결 주소도 확인해야 합니다.',
                '승인된 점검에서는 의뢰서에 명시된 공개 자산과 읽기 전용 canary만 요청해야 합니다. 임의 내부 주소를 추측하거나 포트를 훑는 행동은 같은 기술 검증이라도 승인 범위를 벗어납니다.',
            ],
            'diagram' => '/assets/lessons/server-trust-chain.svg',
            'table' => [
                'columns' => ['요청 위치', '접근 가능한 대상', '위험'],
                'rows' => [
                    ['사용자 브라우저', '공개 웹과 브라우저가 허용한 네트워크', '직접 요청의 출처가 사용자에게 보임'],
                    ['미리보기 서버', '공개 웹 + 내부 서비스', '서버 권한으로 의도하지 않은 요청 가능'],
                    ['metadata 서비스', '내부에서만 접근하도록 설계', '자격 증명과 설정 유출 가능'],
                    ['점검용 canary', '의뢰서에 지정된 읽기 전용 응답', '영향을 제한하면서 서버 측 접근 여부 확인'],
                ],
            ],
            'code' => [
                'language' => 'http',
                'content' => "POST /lumen/cards HTTP/1.1\nHost: preview.lumen-studio.training\nContent-Type: application/x-www-form-urlencoded\n\nurl=https%3A%2F%2Fcdn.example%2Fcampaign-card.png\n\n응답에서 요청 주체와 최종 연결 대상을 구분해 기록하세요.",
            ],
        ],
        'resources' => [
            ['label' => 'PortSwigger · SSRF', 'url' => 'https://portswigger.net/web-security/ssrf'],
            ['label' => 'OWASP · SSRF Prevention Cheat Sheet', 'url' => 'https://cheatsheetseries.owasp.org/cheatsheets/Server_Side_Request_Forgery_Prevention_Cheat_Sheet.html'],
        ],
        'hints' => [
            ['level' => 1, 'title' => '누가 요청하는가', 'body' => '결과 로그의 requester 항목을 보세요. 입력한 URL은 브라우저가 아니라 preview-worker가 가져옵니다.'],
            ['level' => 2, 'title' => '내부 자산 단서', 'body' => '정상 카드의 가져오기 영수증과 자산 참조에서 미리보기 서버만 접근하는 canary 주소를 찾으세요.'],
            ['level' => 3, 'title' => '지정된 canary 확인', 'body' => '확인한 읽기 전용 canary URL을 카드 주소로 제출하고, 브라우저가 아닌 미리보기 서버의 응답이 반환되는지 확인하세요.'],
        ],
        'lab' => ['type' => 'virtual_network'],
        'completion' => [
            'event' => 'metadata_proof_fetched',
            'email' => [
                'subject' => '[Lumen] 내부 metadata 응답 노출',
                'preview' => '사용자가 서버의 네트워크 시야를 빌렸습니다. URL 검증과 egress 통제가 함께 필요합니다.',
            ],
        ],
    ],
    [
        'id' => 'web-v1-11-operation-nightfall',
        'module' => '04-operation',
        'order' => 110,
        'title' => '최종 작전: 나이트폴',
        'eyebrow' => '모듈 4 · 종합 작전',
        'difficulty' => '중급',
        'minutes' => 70,
        'prerequisites' => ['web-v1-10-ssrf'],
        'client' => '나이트폴 관제 포털',
        'story' => '나이트폴 도시안전관제센터는 야간 조명·비상 통신 점검 보고서를 RelayOps 포털에서 공유합니다. 새벽 02시 17분, 외부 유지보수 계정의 세션에서 계정 소유자가 배정받지 않은 보고서와 제한된 운영 문서가 차례로 열렸고, 마지막에는 관리자 전용 증거 vault 접근 기록이 남았습니다. 실제 제어 요청은 관제망에서 차단됐지만 보고서와 운영 정책의 연쇄 노출만으로 관리자 권한에 도달할 수 있는지 즉시 확인해야 합니다.',
        'brief' => '제공된 외부 유지보수 계정으로 Nightfall RelayOps를 블랙박스 점검하세요. 실제 보고서 포털을 사용하면서 브라우저 개발자 도구나 로컬 프록시로 자신의 요청·응답을 관찰하고, 화면에서 얻은 증거만 다음 검증에 사용하세요. 관리자 역할을 정식으로 부여받지 않은 상태에서 evidence vault에 도달할 수 있는지 확인하고 각 권한 경계의 증거를 순서대로 보존하세요.',
        'target' => [
            'objective' => '외부 유지보수 계정에서 시작해 서로 연결된 권한 경계 실패를 재현하고 관리자 전용 evidence vault 접근 증거를 확보하세요.',
            'entry_url' => '/nightfall/reports',
            'service_name' => 'Nightfall RelayOps',
            'hostname' => 'ops.nightfall-grid.training',
            'entry_path' => '/reports',
            'access_method' => '의뢰용 외부 유지보수 계정으로 RelayOps 보고서 포털 접속',
            'environment' => '야간 점검 보고서·운영 문서 서비스 · 조명과 비상 통신 제어망은 별도 인증 구간으로 분리',
            'surface' => '보고서 소유권 · 운영 문서 접근 · 세션 무결성 · 관리자 evidence vault',
        ],
        'email' => [
            'subject' => '[NIGHTFALL / 즉시 대응] 외부 유지보수 계정의 관리자 vault 접근 흔적',
            'sender' => ['name' => '차주원', 'role' => '야간 관제 정보보호 총괄', 'organization' => '나이트폴 도시안전관제센터', 'address' => 'juwon.cha@nightfall-grid.training'],
            'urgency' => '최상 · 02:30~04:00 승인된 검증 창, 교대 전 1차 판단 필요',
            'contact_context' => '관제센터장·법무 당직자·인프라 책임자가 아래 RelayOps 자산에 대한 공동 승인을 완료했습니다. 실제 조명과 비상 통신 제어망은 별도 인증 구간에 있으며, 이번 작업은 포털에서 확인 가능한 읽기 전용 증거에 한정합니다.',
            'scope' => ['ops.nightfall-grid.training의 보고서·운영 문서 열람·세션 검증·evidence vault 화면만 대상', '제공된 유지보수 계정으로 화면에 드러난 참조값을 사용하는 수동 읽기 요청과 자신의 세션 요청 변경 허용', '제어 명령, 보고서 수정·삭제, 계정 열거, 다른 host·사용자 토큰·표시되지 않은 자료 탐색은 범위 외'],
            'deliverables' => ['유지보수 계정과 다른 소유자의 보고서가 열린 요청·응답 및 소유자 불일치 증거', '제한 운영 문서가 같은 계정에 반환된 기록과 그 정보가 다음 권한 경계에 미친 영향', '관리자 역할 없이 evidence vault가 열린 최종 증거와 각 경계를 끊는 수정 우선순위'],
            'cautions' => ['각 단계의 출력을 기록하되 화면 증거에 없는 ID·파일명·계정을 자동 탐색하지 마세요.', 'vault가 열리면 추가 자료를 조회하거나 변경 요청을 보내지 말고 즉시 완료 증거를 제출하세요.'],
            'closing' => '단일 취약점 이름보다 보고서 소유권, 운영 문서 경계, 세션 무결성이 어떻게 연결됐는지를 시간순으로 보고해 주세요. 완료 즉시 당직 팀이 조치 회의를 시작합니다.',
            'cta_label' => 'Nightfall RelayOps 외부 유지보수 콘솔에 접속',
        ],
        'objectives' => [
            '관찰한 증거에서 다음 공격 가설을 세우고 결과로 가설을 갱신한다.',
            '여러 개의 낮은 수준 취약점이 연결되어 높은 영향의 권한 상승이 되는 과정을 설명한다.',
            '각 경계에서 필요한 방어가 하나의 취약점 패치보다 넓어야 함을 정리한다.',
        ],
        'lesson' => [
            'summary' => '학습 노트 · 실전형 분석은 취약점 목록을 대입하는 일이 아니라 자산, 신뢰 경계, 증거와 상태 변화를 연결하는 일입니다.',
            'paragraphs' => [
                '첫 화면에는 내 보고서와 최근 활동만 있습니다. 요청 파라미터, 응답 데이터, 파일 경로처럼 관찰 가능한 사실을 기록하고 어떤 서버 측 검사가 빠졌을지 가설을 세우세요.',
                '다른 보고서에서 얻은 파일 경로는 파일 뷰어의 기준 디렉터리를 알려 줍니다. verifier 설정은 토큰 검증기의 algorithm 처리 방식을 설명합니다. 각 단계의 출력이 다음 단계의 입력이 됩니다.',
                '연쇄 검증에서는 마지막 화면만 남기지 말고 각 단계의 로그인 사용자, 요청, 반환된 정보와 다음 가설을 시간순으로 기록해야 합니다. 그래야 우연한 화면 노출과 실제 권한 상승 경로를 구분할 수 있습니다.',
            ],
            'diagram' => '/assets/lessons/server-trust-chain.svg',
            'table' => [
                'columns' => ['증거', '가설', '다음 검증'],
                'rows' => [
                    ['보고서 URL에 report_id 존재', '객체 소유권 검사가 약할 수 있음', '활동 로그의 다른 ID 요청'],
                    ['외부 보고서에 운영 문서 참조', '뷰어의 허용 문서 경계가 약할 수 있음', '현재 서비스에서 지정 문서 한 건 확인'],
                    ['운영 문서에 무결성 검사 예외', '세션 권한 값을 신뢰할 수 없을 수 있음', '원래 대상·범위를 유지한 권한 검증'],
                    ['관리자 토큰 승인', 'vault 접근 조건 충족', '연쇄 이벤트와 함께 vault 요청'],
                ],
            ],
            'code' => [
                'language' => 'http',
                'content' => "GET /nightfall/reports HTTP/1.1\nHost: ops.nightfall-grid.training\nCookie: relay_session=<redacted>\n\n분석 기록\n1. 현재 로그인 사용자와 허용된 보고서를 확인한다.\n2. 화면과 응답에서 관찰한 사실만 근거로 다음 요청을 세운다.\n3. 각 권한 경계의 요청·응답을 시간순으로 보존한다.",
            ],
        ],
        'resources' => [
            ['label' => 'PortSwigger · Access control', 'url' => 'https://portswigger.net/web-security/access-control'],
            ['label' => 'PortSwigger · Web Security Academy', 'url' => 'https://portswigger.net/web-security'],
            ['label' => 'OWASP · Authorization Cheat Sheet', 'url' => 'https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html'],
        ],
        'hints' => [
            ['level' => 1, 'title' => '증거부터 기록하기', 'body' => '내 보고서를 열어 URL의 선택자와 최근 활동의 다른 보고서 번호를 비교하세요. 공격 이름보다 입력과 결과를 먼저 기록하세요.'],
            ['level' => 2, 'title' => '출력이 다음 입력', 'body' => '다른 보고서 본문에는 운영자가 참조한 verifier 설정 파일의 상대 위치가 있습니다. 파일 뷰어의 public 기준 경로와 연결하세요.'],
            ['level' => 3, 'title' => '마지막 신뢰 경계', 'body' => '운영 문서에서 확인한 검증 예외가 세션 무결성에 미치는 영향을 살펴보세요. 원래 대상과 범위는 유지한 채 권한 값 변경이 승인되는지 확인하고 vault가 열리면 즉시 중단하세요.'],
        ],
        'lab' => ['type' => 'final_chain'],
        'completion' => [
            'event' => 'nightfall_vault_opened',
            'email' => [
                'subject' => '[NIGHTFALL] 작전 종료 · 관제 vault 확보',
                'preview' => '객체 접근, 파일 경로, 토큰 무결성의 세 경계를 연결해 최종 작전을 완료했습니다.',
            ],
        ],
    ],
];
